package erland.webapp.stocks.bl.logic.broker.sb;
/*
 * Copyright (C) 2003 Erland Isaksson (erland_i@hotmail.com)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

import erland.webapp.stocks.bl.logic.broker.BrokerConnectionInterface;
import erland.webapp.stocks.bl.logic.broker.BrokersStockEntry;
import erland.webapp.common.WebAppEnvironmentInterface;
import erland.util.Log;

import java.net.URL;
import java.net.URLConnection;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Locale;

public class SBConnection implements BrokerConnectionInterface {
    private WebAppEnvironmentInterface environment;
    private final static BrokersStockEntry[] availableStocks = new BrokersStockEntry[]{
        new BrokersStockEntry("SE0000449068", "A Brand New World in Sweden  AB ser. B,ABNW B"),
        new BrokersStockEntry("SE0000750010", "A Brand New World in Sweden AB BT ser. B,ABNW BTB"),
        new BrokersStockEntry("SE0000750002", "A Brand New World in Sweden AB TR ser. B,ABNW TRB"),
        new BrokersStockEntry("3966", "ABB Ltd,ABB"),
        new BrokersStockEntry("CH0003846620", "ABB Ltd,ABB"),
        new BrokersStockEntry("SE0000625568", "ABB Ltd ser. U,ABB U"),
        new BrokersStockEntry("22931", "ABB LTD TR 2003,ABB TR"),
        new BrokersStockEntry("13523", "AcadeMedia AB ser. B,ACAD B"),
        new BrokersStockEntry("981", "AcandoFrontec AB ser. B.,AFAB B"),
        new BrokersStockEntry("4287", "A-Com AB,ACOM"),
        new BrokersStockEntry("22532", "A-COM BT (A0312),ACOM BT"),
        new BrokersStockEntry("22531", "A-COM TR 2003,ACOM TR"),
        new BrokersStockEntry("877", "Active Biotech AB,ACTI"),
        new BrokersStockEntry("876", "Active Biotech AB ser. A,ACTI A"),
        new BrokersStockEntry("877", "Active Biotech AB ser. B,ACTI B"),
        new BrokersStockEntry("19074", "Active Capital AB ser A IR,ACAP IRA"),
        new BrokersStockEntry("19079", "Active Capital AB ser B IR,ACAP IRB"),
        new BrokersStockEntry("20016", "Active Capital AB ser. A,ACAP A"),
        new BrokersStockEntry("20017", "Active Capital AB ser. B,ACAP B"),
        new BrokersStockEntry("SE0000331225", "Adcore AB,ADCO"),
        new BrokersStockEntry("3887", "AddNode AB ser. B,ANOD B"),
        new BrokersStockEntry("14336", "Addtech AB ser. B,ADDT B"),
        new BrokersStockEntry("1449", "addVise Inredning Skyddsvent. AB ser. B,ADDV B"),
        new BrokersStockEntry("24915", "AFFÄRSSTRAT. TRB 2004,AFFS TRB"),
        new BrokersStockEntry("878", "Affärsstrategerna AB ser. B,AFFS B"),
        new BrokersStockEntry("24916", "AFFÄRSTRAT. BTB (A0407),AFFS BTB"),
        new BrokersStockEntry("25170", "Ainax AB,AINX"),
        new BrokersStockEntry("SE0000645954", "Airbite AB"),
        new BrokersStockEntry("SE0000227258", "Akzo Nobel N. V. SDB,AKZO"),
        new BrokersStockEntry("SE0000147480", "Alcatel Alsthom Comp. Gen dÉ,ALCA"),
        new BrokersStockEntry("18634", "Alfa Laval AB,ALFA"),
        new BrokersStockEntry("SE0000364283", "Alfaskop AB,ALFA"),
        new BrokersStockEntry("3924", "All Cards Service Center - ACSC AB,ACSC"),
        new BrokersStockEntry("SE0000100364", "Allgon AB ser. B,ALLG B"),
        new BrokersStockEntry("23266", "Altima AB,ALTI"),
        new BrokersStockEntry("5110", "Anoto Group AB,ANOT"),
        new BrokersStockEntry("19828", "ANOTO GROUP TR (A0210),ANOT TR"),
        new BrokersStockEntry("SE0001050428", "ARCAM TRB (NGM) (A0304)"),
        new BrokersStockEntry("SE0000429706", "ARETE AB,ARET"),
        new BrokersStockEntry("23110", "ARRAY BTB (NYAM) (A0401),ARRA BTB"),
        new BrokersStockEntry("SE0000275943", "Artema Medical AB ser. B,ARTM B"),
        new BrokersStockEntry("SE0000477192", "Artika AB,ATMG B"),
        new BrokersStockEntry("953", "Artimplant AB ser. B,ARTI B"),
        new BrokersStockEntry("23598", "Artimplant BTA,ARTI BT0123"),
        new BrokersStockEntry("20868", "ARTIMPLANT BTB (A0303),ARTI BTB"),
        new BrokersStockEntry("20868", "ARTIMPLANT BTB (A0402),ARTI BTB"),
        new BrokersStockEntry("20867", "ARTIMPLANT TRB (A0303),ARTI TRB"),
        new BrokersStockEntry("20867", "ARTIMPLANT TRB 2003 2,ARTI TRB"),
        new BrokersStockEntry("13291", "Aspiro AB,ASP"),
        new BrokersStockEntry("SE0000695454", "Aspiro AB BT,ASP BT"),
        new BrokersStockEntry("SE0000695447", "Aspiro AB TR,ASP TR"),
        new BrokersStockEntry("20562", "ASPIRO BT (A0302),ASP BT"),
        new BrokersStockEntry("20562", "ASPIRO BT 2 (A0311),ASP BT"),
        new BrokersStockEntry("22327", "ASPIRO TR (A0310),ASP TR"),
        new BrokersStockEntry("22327", "ASPIRO TR 2004,ASP TR"),
        new BrokersStockEntry("402", "ASSA ABLOY AB ser. B,ASSA B"),
        new BrokersStockEntry("3524", "AstraZeneca PLC,AZN"),
        new BrokersStockEntry("45", "Atlas Copco AB ser. A,ATCO A"),
        new BrokersStockEntry("46", "Atlas Copco AB ser. B,ATCO B"),
        new BrokersStockEntry("SE0000195802", "Atle AB,ATLE"),
        new BrokersStockEntry("5489", "AudioDev AB ser B,AUDV B"),
        new BrokersStockEntry("SE0000948614", "AUREX BT (NGM) (A0210),AURX BT"),
        new BrokersStockEntry("SE0000948606", "AUREX TR (A0207),AURX TR"),
        new BrokersStockEntry("SE0000674509", "AU-System AB,AUS"),
        new BrokersStockEntry("SE0000579591", "Autofill AB,AFIL"),
        new BrokersStockEntry("47", "Autoliv Inc. SDB,ALIV"),
        new BrokersStockEntry("988", "Avanza AB,AZA"),
        new BrokersStockEntry("SE0000101047", "Avesta Sheffield"),
        new BrokersStockEntry("SE0000101057", "Avesta Sheffield AB,AVES"),
        new BrokersStockEntry("SE0000899874", "Avesta Sheffield AB Tvångsinlösenaktie,AVES OTC"),
        new BrokersStockEntry("FI0009009674", "AvestaPolarit Abp,AVPO"),
        new BrokersStockEntry("4590", "Axfood AB,AXFO"),
        new BrokersStockEntry("5150", "Axis AB,AXIS"),
        new BrokersStockEntry("964", "B&amp;N Nordsjöfrakt AB ser. B,BN B"),
        new BrokersStockEntry("SE0000469769", "Balder, Fastighets AB,BALD"),
        new BrokersStockEntry("19096", "Ballingslöv International AB,BALL"),
        new BrokersStockEntry("SE0000537086", "Barnfamiljen.com AB ser. B,BARN B"),
        new BrokersStockEntry("SE0000169070", "Bayer Aktiengesellschaft,BAYE"),
        new BrokersStockEntry("SE0000514556", "Bedminster AB ser. B,BMIN B"),
        new BrokersStockEntry("792", "Beijer AB, G &amp; L ser. B,BEIJ B"),
        new BrokersStockEntry("875", "Beijer Alma AB ser. B,BEIA B"),
        new BrokersStockEntry("5081", "Beijer Electronics AB,BELE"),
        new BrokersStockEntry("891", "Berg &amp; Co, AB, C F ser. B,BRG B"),
        new BrokersStockEntry("793", "Bergman &amp; Beving AB ser. B,BERG B"),
        new BrokersStockEntry("958", "Biacore International AB,BCOR"),
        new BrokersStockEntry("794", "Bilia AB ser. A,BILI A"),
        new BrokersStockEntry("14922", "Billerud AB,BILL"),
        new BrokersStockEntry("SE0000393720", "Binar AB,BINA"),
        new BrokersStockEntry("959", "BioGaia AB ser. B,BIOG B"),
        new BrokersStockEntry("13348", "BioInvent International AB,BINV"),
        new BrokersStockEntry("SE0001124389", "BIOLIGHT BTB (NGM) (A0401),BIOL BTB"),
        new BrokersStockEntry("SE0000310682", "Biolight Int. AB serie A,BIOL A"),
        new BrokersStockEntry("SE0001124371", "BIOLIGHT TRB (NGM) (A0311)"),
        new BrokersStockEntry("1019", "Biolin AB,BLIN"),
        new BrokersStockEntry("22466", "BIOLIN BTU (A0311),BLIN BTU"),
        new BrokersStockEntry("22464", "BIOLIN UR (A0310),BLIN UR"),
        new BrokersStockEntry("960", "BioPhausia AB,BIOP"),
        new BrokersStockEntry("SE0000293656", "BioPhausia AB ser. A,BIOP A"),
        new BrokersStockEntry("22315", "BIOPHAUSIA TR 2003,BIOP TR"),
        new BrokersStockEntry("SE0000361909", "Biora AB,BIOR"),
        new BrokersStockEntry("5209", "Biotage AB ser. A,BIOT A"),
        new BrokersStockEntry("SE0000653404", "BlueMarx AB,BLX"),
        new BrokersStockEntry("BQ0000111115", "Bo Drott 040414-Termin,DROT TAA"),
        new BrokersStockEntry("BQ0000111117", "Bo Drott 040511-Termin,BDRO T"),
        new BrokersStockEntry("24541", "BO DROTT IR 2004,BDRO IR"),
        new BrokersStockEntry("15285", "Boliden AB,BOL"),
        new BrokersStockEntry("24140", "BOLIDEN BT 2004,BOL BT"),
        new BrokersStockEntry("SE0000558470", "Boliden Limited, SDB,BOL"),
        new BrokersStockEntry("4690", "BOLIDEN TR 2004,BOL TR"),
        new BrokersStockEntry("892", "Bong Ljungdahl AB,BONG"),
        new BrokersStockEntry("18683", "BONG LJUNGDAHL TR 02,BONG TR"),
        new BrokersStockEntry("893", "Borås Wäfveri AB ser. B,WAFV B"),
        new BrokersStockEntry("3982", "Boss Media AB,BOSS"),
        new BrokersStockEntry("4859", "Bringwell International AB,BWL"),
        new BrokersStockEntry("22922", "Brinova Fastigheter AB ser.B,BRIN B"),
        new BrokersStockEntry("22533", "BRINOVA IRA 2003,BRIN IRA"),
        new BrokersStockEntry("22534", "BRINOVA IRB 2003,BRIN IRB"),
        new BrokersStockEntry("894", "BRIO AB ser. B,BRIO B"),
        new BrokersStockEntry("962", "Broström AB ser.B,BRO B"),
        new BrokersStockEntry("SE0000291171", "BT Industries AB,BTI"),
        new BrokersStockEntry("13288", "BTS Group AB ser. B,BTS B"),
        new BrokersStockEntry("SE0000123267", "Bulten AB ser. B,BULT B"),
        new BrokersStockEntry("800", "Bure Equity AB,BURE"),
        new BrokersStockEntry("21431", "BURE EQUITY BTU (A0307),BURE BTU"),
        new BrokersStockEntry("21430", "BURE EQUITY UR 2003,BURE UR"),
        new BrokersStockEntry("NULL", "Capinordic A/S,CAPI"),
        new BrokersStockEntry("11116", "Capio AB,CAP"),
        new BrokersStockEntry("3245", "Capona AB,CAPO"),
        new BrokersStockEntry("801", "Cardo AB,CARD"),
        new BrokersStockEntry("DK0010221803", "Carli  Gry International A/S,CGIA"),
        new BrokersStockEntry("13235", "Carnegie &amp; Co AB, D.,CAR"),
        new BrokersStockEntry("SE0000522823", "Cartesia Informationsteknik AB ser. B,CART B"),
        new BrokersStockEntry("4983", "Cash Guard AB ser. B,CASH B"),
        new BrokersStockEntry("22249", "CASH GUARD BTB (A0312),CASH BTB"),
        new BrokersStockEntry("22248", "CASH GUARD TRB 2003,CASH TRB"),
        new BrokersStockEntry("SE0000523441", "Castcom AB,CCOM"),
        new BrokersStockEntry("966", "Castellum AB,CAST"),
        new BrokersStockEntry("13223", "CELL NETWORK TR (A0106),CELL TR"),
        new BrokersStockEntry("SE0000769044", "CellPoint Inc, SDB,CLPT"),
        new BrokersStockEntry("SE0000723652", "Centrcourt AB BT,CENT BT"),
        new BrokersStockEntry("SE0000519928", "Centrecourt AB,CENT"),
        new BrokersStockEntry("5121", "Cherryföretagen AB ser. B,CHER B"),
        new BrokersStockEntry("20067", "CHERRYFÖRETAGEN TRB,CHER TRB"),
        new BrokersStockEntry("SE0001186545", "CISL GR. BT (TORGET) (A0406),CISL BT"),
        new BrokersStockEntry("24635", "CISL GR. TR (TORGET) (A0404),CISL TR"),
        new BrokersStockEntry("4145", "Clas Ohlson AB ser. B,CLAS B"),
        new BrokersStockEntry("969", "Cloetta Fazer AB ser. B,CFA B"),
        new BrokersStockEntry("SE0000672040", "Coldator FreshCool Int. AB,COLD B"),
        new BrokersStockEntry("SE0000653495", "Comexchange Commercial Exchanges AB,COMX"),
        new BrokersStockEntry("971", "Concordia Maritime AB ser. B,CCOR B"),
        new BrokersStockEntry("19479", "Connecta AB,CNTA"),
        new BrokersStockEntry("SE0000585960", "Connecta AB ser. B,CNTA B"),
        new BrokersStockEntry("21599", "CONNECTA TR (NYAM),CNTA TR"),
        new BrokersStockEntry("803", "Consilium AB ser. B,CONS B"),
        new BrokersStockEntry("13293", "CONSILIUM TRV B (A0205),CONS TRVB"),
        new BrokersStockEntry("SE0000324428", "CTC Medical AB"),
        new BrokersStockEntry("3081", "CTT Systems AB,CTT"),
        new BrokersStockEntry("5362", "CTT SYSTEMS BT (A0401),CTT BT"),
        new BrokersStockEntry("14932", "CUSTOS IL (A0209),CUST IL"),
        new BrokersStockEntry("14679", "CUSTOS SR1 (A0208),CUST SR1"),
        new BrokersStockEntry("14679", "CUSTOS SR1 (A0306),CUST SR1"),
        new BrokersStockEntry("14679", "CUSTOS SR1 2003 2,CUST SR1"),
        new BrokersStockEntry("5280", "Custos, AB,CUST"),
        new BrokersStockEntry("SE0000103046", "Custos, AB ser. B,CUST B"),
        new BrokersStockEntry("4345", "Cybercom Group Europe AB,CYBE"),
        new BrokersStockEntry("SE0000665937", "Cycore AB"),
        new BrokersStockEntry("SE0000733917", "Daydream Software AB BTB,DAYD BTB"),
        new BrokersStockEntry("11637", "Daydream Software AB ser. B,DAYD B"),
        new BrokersStockEntry("SE0000733909", "Daydream Software AB TRB,DAYD TRB"),
        new BrokersStockEntry("SE0000402497", "Decim AB ser. B,DECI B"),
        new BrokersStockEntry("SE0000750556", "Decim AB TR ser. B,DECI TRB"),
        new BrokersStockEntry("SE0000591836", "Dentronic AB TR ser. B,DENT TRB"),
        new BrokersStockEntry("SE0000384042", "Dial nn Smile AB,DIAL OTC"),
        new BrokersStockEntry("SE0000410698", "Dial NXT Group AB ser. B,DNG B"),
        new BrokersStockEntry("SE0000724809", "Dial NXT Group AB ser. B BT,DIAL BTB"),
        new BrokersStockEntry("SE0000724791", "Dial NXT Group AB TR ser. B,DIAL TRB"),
        new BrokersStockEntry("24918", "DIAMYD MED. BTB (A0406),DIAM BTB"),
        new BrokersStockEntry("24917", "DIAMYD MED. TRB 2004,DIAM TRB"),
        new BrokersStockEntry("18765", "Diamyd Medical AB ser. B,DIAM B"),
        new BrokersStockEntry("SE0000325870", "Diffchamb AB,DIFF"),
        new BrokersStockEntry("SE0000436685", "Digital Illusions CE AB,DICE"),
        new BrokersStockEntry("1446", "Digital Illusions CE AB ser. A,DICE A"),
        new BrokersStockEntry("3571", "Digital Vision AB,DV"),
        new BrokersStockEntry("17848", "DIGITAL VISION TR (A0203),DV TR"),
        new BrokersStockEntry("17848", "DIGITAL VISION TR 2004,DV TR"),
        new BrokersStockEntry("SE0000338220", "Diligentia AB,DILI"),
        new BrokersStockEntry("12499", "Dimension AB,DMSN"),
        new BrokersStockEntry("SE0001198771", "DISPLAIT BT (NGM) (A0407),DSP BT"),
        new BrokersStockEntry("SE0001105768", "DISPLAYIT BT (NGM) (A0312)"),
        new BrokersStockEntry("SE0001198763", "DISPLAYIT TR (NGM) (A0406),DSP TR"),
        new BrokersStockEntry("SE0000226607", "Diös AB, Anders,DIOS"),
        new BrokersStockEntry("SE0001011263", "Dometic International AB,DOMC"),
        new BrokersStockEntry("SE0000215493", "DORO AB,DORO"),
        new BrokersStockEntry("896", "DORO AB ser. A,DORO A"),
        new BrokersStockEntry("24909", "Drott, Bostadsaktiebolaget,BDRO"),
        new BrokersStockEntry("4005", "Duroc AB ser. B,DURC B"),
        new BrokersStockEntry("SE0000593956", "DYNARC (SIX) (A0205),DYRC"),
        new BrokersStockEntry("11463", "Ecovision AB ser. B,ECOV B"),
        new BrokersStockEntry("SE0000545501", "Ecta Resurs AB ser. A,ECTA A"),
        new BrokersStockEntry("SE0000538605", "Ecta Resurs AB ser. B,ECTA B"),
        new BrokersStockEntry("SE0000933087", "ECTA RESURS BTA (A0207),ECTA BTA"),
        new BrokersStockEntry("SE0000933103", "ECTA RESURS BTB (A0207),ECTA BTB"),
        new BrokersStockEntry("SE0000933079", "ECTA RESURS TRA (NGM) (A0206),ECTA TRA"),
        new BrokersStockEntry("SE0000933095", "ECTA RESURS TRB (NGM) (A0206),ECTA TRB"),
        new BrokersStockEntry("3518", "Effnet Group AB,EFFN"),
        new BrokersStockEntry("897", "Elanders AB ser. B,ELAN B"),
        new BrokersStockEntry("3872", "Electrolux AB ser. BE,ELUX BE"),
        new BrokersStockEntry("24792", "ELECTROLUX ILA 2004,ELUX ILA"),
        new BrokersStockEntry("24793", "ELECTROLUX ILB 2004,ELUX ILB"),
        new BrokersStockEntry("24790", "ELECTROLUX SRA (A0405),ELUX SRA"),
        new BrokersStockEntry("24791", "ELECTROLUX SRB (A0405),ELUX SRB"),
        new BrokersStockEntry("80", "Electrolux, AB ser. A,ELUX A"),
        new BrokersStockEntry("81", "Electrolux, AB ser. B,ELUX B"),
        new BrokersStockEntry("806", "Elekta AB ser. B,EKTA B"),
        new BrokersStockEntry("23195", "ELEKTA ILB (A0403),EKTA ILB"),
        new BrokersStockEntry("22428", "ELEKTA SR1 2003,EKTA SR1"),
        new BrokersStockEntry("899", "ElektronikGruppen BK AB ser. B,ELGR B"),
        new BrokersStockEntry("1149", "Enea AB,ENEA"),
        new BrokersStockEntry("4931", "ENEA TR 2003,ENEA TR"),
        new BrokersStockEntry("11046", "Eniro AB,ENRO"),
        new BrokersStockEntry("21057", "ENIRO SR 2004,ENRO SR"),
        new BrokersStockEntry("4212", "Enlight AB ser. B,ENLI B"),
        new BrokersStockEntry("13379", "ENLIGHT TRB 2002,ENLI TRB"),
        new BrokersStockEntry("SE0000538258", "Entra Data AB ser. A,ENTR A"),
        new BrokersStockEntry("SE0000619496", "E-Play AB,EPLY"),
        new BrokersStockEntry("SE0000809741", "Epsilon AB ser. B,EPSI B"),
        new BrokersStockEntry("19452", "ERICSSON TRB (A0208),ERIC TRB"),
        new BrokersStockEntry("100", "Ericsson, Telefonab. L M ser. A,ERIC A"),
        new BrokersStockEntry("101", "Ericsson, Telefonab. L M ser. B,ERIC B"),
        new BrokersStockEntry("SE0000104051", "Esselte AB ser. A,SLT A"),
        new BrokersStockEntry("SE0000104077", "Esselte AB ser. B,SLT B"),
        new BrokersStockEntry("SE0000514515", "Estinvest AB,ESTI"),
        new BrokersStockEntry("SE0001046061", "EURIS TRB (NGM) (A0303),EURI TRB"),
        new BrokersStockEntry("SE0000237315_", "Europolitan Vodafone AB,EURO"),
        new BrokersStockEntry("SE0000110835", "Evidentia Fastigheter AB ser. A,EVID A"),
        new BrokersStockEntry("SE0000169195", "Evidentia Fastigheter AB ser. B,EVID B"),
        new BrokersStockEntry("SE0000295644", "Exave AB ser. B"),
        new BrokersStockEntry("1049", "Expanda AB ser. B,EXPA B"),
        new BrokersStockEntry("SE0000169435", "F÷rsSkringsaktiebolaget Svenska Brand"),
        new BrokersStockEntry("BQ0000111116", "Fabege 040405-Termin,FABG TB"),
        new BrokersStockEntry("974", "Fabege AB ser. A,FABG A"),
        new BrokersStockEntry("975", "Fabege AB ser. B,FABG B"),
        new BrokersStockEntry("24846", "FABEGE ILA 2004,FABG ILA"),
        new BrokersStockEntry("24847", "FABEGE ILB 2004,FABG ILB"),
        new BrokersStockEntry("24844", "FABEGE SRA (A0405),FABG SRA"),
        new BrokersStockEntry("24845", "FABEGE SRB (A0405),FABG SRB"),
        new BrokersStockEntry("SE0001134644", "FACILE BTB (NGM) (A0403),FACL BTB"),
        new BrokersStockEntry("903", "Fagerhult, AB,FAG"),
        new BrokersStockEntry("980", "Fast Partner AB,FPAR"),
        new BrokersStockEntry("SE0000135303", "Fastighets AB Celtica,CELT"),
        new BrokersStockEntry("SE0000431009", "FB Industri Holding AB ser. B,FBI B"),
        new BrokersStockEntry("5053", "Feelgood Svenska AB,FEEL"),
        new BrokersStockEntry("905", "Fenix Outdoor AB ser. B,FIX B"),
        new BrokersStockEntry("4870", "Fingerprint Cards AB ser. B,FING B"),
        new BrokersStockEntry("811", "Finnveden AB ser. B,FVED B"),
        new BrokersStockEntry("14555", "FINNVEDEN TR B (A0110),FVED TRB"),
        new BrokersStockEntry("20554", "Fly Me Europe AB ser. B,FLY B"),
        new BrokersStockEntry("25229", "FLY ME EUROPE TRB (NYAM),FLY TRB"),
        new BrokersStockEntry("SE0000104846", "Folkebolagen AB ser. B,FOLK B"),
        new BrokersStockEntry("SE0001049925", "FORMO MED. BT (A0307),FORM BT"),
        new BrokersStockEntry("SE0000789455", "FORMO MEDICAL TR (A0104),FORM TR"),
        new BrokersStockEntry("24444", "FormPipe AB,FPIP"),
        new BrokersStockEntry("24444", "FormPipe AB,FPIP"),
        new BrokersStockEntry("24208", "FORMPIPE BT (NYAM) (A0405),FPIP BT"),
        new BrokersStockEntry("24207", "FORMPIPE TR 04 (NYAM),FPIP TR"),
        new BrokersStockEntry("3972", "Framfab AB,FRAM"),
        new BrokersStockEntry("22195", "Framfab AB BT,FRAM BT"),
        new BrokersStockEntry("22195", "FRAMFAB BT (A0406),FRAM BT"),
        new BrokersStockEntry("25050", "FRAMFAB TR 2004,FRAM TR"),
        new BrokersStockEntry("3557", "Frango AB,FRAN B"),
        new BrokersStockEntry("1006", "Freetel AB ser. A,FTEL A"),
        new BrokersStockEntry("1007", "Freetel AB ser. B,FTEL B"),
        new BrokersStockEntry("SE0000601544", "Friluftsbolaget Ekelund &amp; Sagner AB,FRIL"),
        new BrokersStockEntry("SE0000941304", "FRONTYARD BTB (A0210),FROY BTB"),
        new BrokersStockEntry("120", "FöreningsSparbanken AB ser. A,FSPA A"),
        new BrokersStockEntry("140", "Gambro AB ser. A,GAMB A"),
        new BrokersStockEntry("141", "Gambro AB ser. B,GAMB B"),
        new BrokersStockEntry("SE0001149394", "GAMERS P. TRB (SIX) (A0401),GAME TRB"),
        new BrokersStockEntry("812", "Getinge AB ser. B,GETI B"),
        new BrokersStockEntry("813", "Geveko, AB ser. B,GVKO B"),
        new BrokersStockEntry("5042", "Glocalnet AB,GLOC"),
        new BrokersStockEntry("SE0000428179", "Glocalnet AB ser. B,GLOC B"),
        new BrokersStockEntry("13121", "GLOCALNET TR B (A0105),GLOC TRB"),
        new BrokersStockEntry("SE0000880742", "GLYCOREX BTB (NGM) (A0202)"),
        new BrokersStockEntry("SE0001116484", "GLYCOREX BTB (NGM) (A0312),GTAB BTB"),
        new BrokersStockEntry("SE0000880734", "GLYCOREX TRB (NGM) (A0201)"),
        new BrokersStockEntry("908", "Gorthon Lines AB ser. B,GORT B"),
        new BrokersStockEntry("814", "Gotland, Rederiab. ser. A,GOTL A"),
        new BrokersStockEntry("815", "Gotland, Rederiab. ser. B,GOTL B"),
        new BrokersStockEntry("4439", "Graninge AB,GRAN"),
        new BrokersStockEntry("816", "Gunnebo AB,GUNN"),
        new BrokersStockEntry("SE0000350340", "Gylling Optima Batteries AB ser. B,OPTB B"),
        new BrokersStockEntry("24683", "HAGSTRÖMER &amp; QVIB. SR 2004,HAGQ SR"),
        new BrokersStockEntry("5219", "Hagströmer &amp; Qviberg AB,HAGQ"),
        new BrokersStockEntry("817", "Haldex AB,HLDX"),
        new BrokersStockEntry("SE0000383259", "Handelsbanken Hypotek AB pr,HBHY PREF"),
        new BrokersStockEntry("990", "Havsfrun, AB ser. B,HAV B"),
        new BrokersStockEntry("991", "Heba Fastighets AB ser. B,HEBA B"),
        new BrokersStockEntry("SE0001061482", "HEBI H. C TRV (NGM) (A0304),HEBI TRV"),
        new BrokersStockEntry("992", "Hennes &amp; Mauritz AB, H &amp; M ser. B,HM B"),
        new BrokersStockEntry("819", "Hexagon AB ser. B,HEXA B"),
        new BrokersStockEntry("18645", "HEXAGON TRB 2002,HEXA TRB"),
        new BrokersStockEntry("3540", "HiQ International AB,HIQ"),
        new BrokersStockEntry("909", "HL Display AB ser. B,HL B"),
        new BrokersStockEntry("993", "HOIST INTERNATIONAL AB ser. B,HOST B"),
        new BrokersStockEntry("13829", "HOIST TRV B (A0108),HOSTTRVB"),
        new BrokersStockEntry("221", "Holmen AB ser. A,HOLM A"),
        new BrokersStockEntry("222", "Holmen AB ser. B,HOLM B"),
        new BrokersStockEntry("19208", "HQ Fonder AB,HQFO"),
        new BrokersStockEntry("820", "Hufvudstaden AB ser. A,HUFV A"),
        new BrokersStockEntry("821", "Hufvudstaden AB ser. C,HUFV C"),
        new BrokersStockEntry("5369", "Human Care H C AB,HUMA"),
        new BrokersStockEntry("21893", "HUMAN CARE H C AB,HUMA"),
        new BrokersStockEntry("SE0001100819", "HYDROPULSOR TRB (NOTC) (A0309)"),
        new BrokersStockEntry("824", "Höganäs AB ser. B,HOGA B"),
        new BrokersStockEntry("5237", "I.A.R Systems AB,IAR"),
        new BrokersStockEntry("910", "IBS AB ser. B,IBS B"),
        new BrokersStockEntry("18358", "ICON TR (A0204),ICON TR"),
        new BrokersStockEntry("25068", "IDL BIOT. TRB (TORGET) (A0406),IDL TRB"),
        new BrokersStockEntry("SE0000680936", "IDL Biotech AB TR ser. B,IDL TRB"),
        new BrokersStockEntry("SE0000396715", "Independent Media Gr. Sweden AB ser. B,IMG B"),
        new BrokersStockEntry("994", "Industrial and Financial Syst. AB ser. A,IFS A"),
        new BrokersStockEntry("995", "Industrial and Financial Syst. AB ser. B,IFS B"),
        new BrokersStockEntry("SE0000193187", "Industrivärden, AB KVB ser. A,INDU KBA"),
        new BrokersStockEntry("SE0000147696", "Industrivärden, AB KVB ser. C,INDU KBC"),
        new BrokersStockEntry("142", "Industrivärden, AB ser. A,INDU A"),
        new BrokersStockEntry("143", "Industrivärden, AB ser. C,INDU C"),
        new BrokersStockEntry("SE0000686768", "Insite Interactive AB,INSI"),
        new BrokersStockEntry("941", "Intellecta AB ser. B,ICTA B"),
        new BrokersStockEntry("SE0000259418", "Intelligent Micro Systems Data AB,IMS"),
        new BrokersStockEntry("12610", "INTENTIA BTB (A0307),INT BTB"),
        new BrokersStockEntry("997", "Intentia International AB ser. B,INT B"),
        new BrokersStockEntry("12609", "INTENTIA TR B (A0103),INT TRB"),
        new BrokersStockEntry("12609", "INTENTIA TRB 2003,INT TRB"),
        new BrokersStockEntry("18962", "Intrum Justitia AB,IJ"),
        new BrokersStockEntry("23707", "Inwarehouse AB,IWH"),
        new BrokersStockEntry("160", "Investor AB ser. A,INVE A"),
        new BrokersStockEntry("161", "Investor AB ser. B,INVE B"),
        new BrokersStockEntry("998", "Invik &amp; Co AB ser. A,INVK A"),
        new BrokersStockEntry("999", "Invik &amp; Co AB ser. B,INVK B"),
        new BrokersStockEntry("SE0000275802", "IRO AB,IRO"),
        new BrokersStockEntry("SE0001000688", "ISEC TR (TORGET) (A0211),ISEC TR"),
        new BrokersStockEntry("1074", "ITAB Industri AB ser. B,ITAB B"),
        new BrokersStockEntry("25032", "ITAB Shop Concept ser. B,ISC B"),
        new BrokersStockEntry("SE0000107476", "Jacobson &amp; Widmark, AB,JW"),
        new BrokersStockEntry("4869", "JC AB,JC"),
        new BrokersStockEntry("3555", "Jeeves Information Systems AB,JEEV"),
        new BrokersStockEntry("21189", "JLT Mobile Computers AB,JLT"),
        new BrokersStockEntry("SE0000109142", "JM AB,JM B"),
        new BrokersStockEntry("13217", "JM AB,JM"),
        new BrokersStockEntry("SE0000695645", "Jobline International AB,JOBL"),
        new BrokersStockEntry("SE0000689986", "Johnson Pump  AB,JP"),
        new BrokersStockEntry("11326", "Johnson Pump AB ser. A,JP A"),
        new BrokersStockEntry("SE0000393936", "Johnson Pump Int. AB ser. B,JPI B"),
        new BrokersStockEntry("19765", "JOHNSON PUMP TRA 2002,JP TRA"),
        new BrokersStockEntry("SE0000211682", "JP Nordiska AB,JPNO"),
        new BrokersStockEntry("912", "KABE Husvagnar AB ser. B,KABE B"),
        new BrokersStockEntry("SE0000102790", "Kalmar Industries AB,KIND"),
        new BrokersStockEntry("SE0000693731", "Kamera AB,KAME"),
        new BrokersStockEntry("1002", "Karlshamns AB,KAB"),
        new BrokersStockEntry("3927", "Karo Bio AB,KARO"),
        new BrokersStockEntry("SE0000242711", "Karo Bio AB ser. B,KARO B"),
        new BrokersStockEntry("21151", "KARO BIO BT (A0306),KARO BT"),
        new BrokersStockEntry("21150", "KARO BIO TR,KARO TR"),
        new BrokersStockEntry("1004", "Karolin Machine Tool AB,KMT"),
        new BrokersStockEntry("20383", "Kaupþing Búnaðarbanki hf.,KAUP SEK"),
        new BrokersStockEntry("180", "Kinnevik, Industriförvaltnings AB ser. A,KINV A"),
        new BrokersStockEntry("181", "Kinnevik, Industriförvaltnings AB ser. B,KINV B"),
        new BrokersStockEntry("SE0000459067", "Kipling Holding AB,KIPL"),
        new BrokersStockEntry("SE0000120727", "Kjessler &amp; Mannerstråle AB,KM"),
        new BrokersStockEntry("1005", "KLIPPAN AB,KLIP"),
        new BrokersStockEntry("19459", "Klövern AB,KLOV"),
        new BrokersStockEntry("996", "Klövern AB ser. A,KLOV A"),
        new BrokersStockEntry("19459", "Klövern AB ser. B,KLOV B"),
        new BrokersStockEntry("3219", "Know IT AB,KNOW"),
        new BrokersStockEntry("14593", "KNOW IT TR (A0110),KNOW TR"),
        new BrokersStockEntry("3546", "Kungsleden AB,KLED"),
        new BrokersStockEntry("972", "Labs2 Group AB,LABS"),
        new BrokersStockEntry("24072", "Labs2 Group AB,LABS"),
        new BrokersStockEntry("14335", "Lagercrantz Group AB ser B,LAGR B"),
        new BrokersStockEntry("24773", "Lappland Goldminers AB,GOLD"),
        new BrokersStockEntry("913", "Latour, Investmentab. ser. A,LATO A"),
        new BrokersStockEntry("914", "Latour, Investmentab. ser. B,LATO B"),
        new BrokersStockEntry("1406", "LB Icon AB,ICON"),
        new BrokersStockEntry("SE0000922783", "LC-TEC H BT (NGM) (A0209),LCT BT"),
        new BrokersStockEntry("SE0000921926", "LC-TEC HLD TO (NGM) (A0210),LCT TO"),
        new BrokersStockEntry("SE0001126533", "LC-TEC HOLD. TR (NOTC) (A0311),LCT OTC TR"),
        new BrokersStockEntry("900", "Ledstiernan AB ser. B,LEDS B"),
        new BrokersStockEntry("874", "LGP Allgon Holding AB,LGPA"),
        new BrokersStockEntry("SE0000469579", "Lifco AB ser. B,LIF B"),
        new BrokersStockEntry("SE0001050683", "LIFEASSAYS BTB (A0306),LIFE BTB"),
        new BrokersStockEntry("SE0001050675", "LIFEASSAYS TRB (NGM) (A0304),LIFE TRB"),
        new BrokersStockEntry("SE0001182767", "LIGHTLAB BTB (NGM) (A0405)"),
        new BrokersStockEntry("SE0000393894", "Lign Multiwood AB ser. B,LIGN B"),
        new BrokersStockEntry("SE0000349078", "Limt AB"),
        new BrokersStockEntry("SE0000108581", "Lindab AB ser. B,LIND B"),
        new BrokersStockEntry("833", "Lindex, AB,LDEX"),
        new BrokersStockEntry("SE0000311615", "Linné Group AB,LINN"),
        new BrokersStockEntry("SE0000824138", "Live Networks AB ser. B,LIVE B"),
        new BrokersStockEntry("1011", "LjungbergGruppen AB ser. B,LJGR B"),
        new BrokersStockEntry("SE0000731770", "Ludvika Mining AB ser. B,LUMI B"),
        new BrokersStockEntry("1012", "Lundbergföretagen AB, L E ser. B,LUND B"),
        new BrokersStockEntry("SE0000100505", "Lundin Oil AB ser. B,LOIL B"),
        new BrokersStockEntry("22335", "Lundin Petroleum AB,LUPE"),
        new BrokersStockEntry("SE0000861155", "Lundin Petroleum AB BT,LUPE BT"),
        new BrokersStockEntry("15680", "Lundin Petroleum AB TO,LUPE TO"),
        new BrokersStockEntry("SE0000861148", "Lundin Petroleum AB TR,LUPE TR"),
        new BrokersStockEntry("5101", "Luvit AB,LUVA"),
        new BrokersStockEntry("SE0000767972", "Luvit AB BTU,LUVA BTU"),
        new BrokersStockEntry("SE0000767964", "Luvit AB TRU,LUVA TRU"),
        new BrokersStockEntry("19940", "LUVIT BT (NYAM) (A0212),LUVA BT"),
        new BrokersStockEntry("1014", "Luxonen S.A. SDB,LUXO"),
        new BrokersStockEntry("SE0000442931", "M2S Sverige AB ser. B,M2S B"),
        new BrokersStockEntry("3223", "Malmbergs Elektriska AB ser. B,MEAB B"),
        new BrokersStockEntry("1016", "Mandamus Fastigheter AB,MFAS"),
        new BrokersStockEntry("1015", "Mandator AB,MAND"),
        new BrokersStockEntry("21895", "Mandator AB BT,MAND BT"),
        new BrokersStockEntry("21895", "MANDATOR BT (A0405),MAND BT"),
        new BrokersStockEntry("21894", "MANDATOR TR (A0308),MAND TR"),
        new BrokersStockEntry("21894", "MANDATOR TR 2004,MAND TR"),
        new BrokersStockEntry("SE0000232282", "Matteus AB,MATT"),
        new BrokersStockEntry("1018", "Maxim Pharmaceuticals, Inc.,MAXM"),
        new BrokersStockEntry("917", "Meda AB ser. A,MEDA A"),
        new BrokersStockEntry("14765", "MEDA TRA (A0111),MEDA TRA"),
        new BrokersStockEntry("1030", "MEDICOVER Holding S.A SDB,MCOV"),
        new BrokersStockEntry("SE0000680977", "MediRox AB ser. B,MROX B"),
        new BrokersStockEntry("25083", "MediTeam Dental AB,MTD"),
        new BrokersStockEntry("1020", "Medivir AB ser. B,MVIR B"),
        new BrokersStockEntry("24841", "MEDIVIR TRB 2004,MVIR TRB"),
        new BrokersStockEntry("4986", "Mekonomen AB ser. B,MEKO B"),
        new BrokersStockEntry("12429", "Metro International S.A SDB ser. A,MTRO A"),
        new BrokersStockEntry("12430", "Metro International S.A SDB ser. B,MTRO B"),
        new BrokersStockEntry("21816", "METRO SDB TRA,MTRO TRA"),
        new BrokersStockEntry("SE0001171802", "MICRO SYS BTB (NGM) (A0404),MSAB BTB"),
        new BrokersStockEntry("21503", "MICRONIC L. SYS. BT (A0307),MICR BT"),
        new BrokersStockEntry("21502", "MICRONIC LASER SYST. TR,MICR TR"),
        new BrokersStockEntry("4714", "Micronic Laser Systems AB,MICR"),
        new BrokersStockEntry("834", "Midway Holding AB ser. A,MIDW A"),
        new BrokersStockEntry("835", "Midway Holding AB ser. B,MIDW B"),
        new BrokersStockEntry("24507", "Millicom International Cellular S.A. SDB,MIC"),
        new BrokersStockEntry("SE0000673998", "Mind AB,MIND"),
        new BrokersStockEntry("SE0000587339", "Miss Mary of Sweden Holding AB"),
        new BrokersStockEntry("SE0000941122", "MNW RECORDS BT (A0210),MNW BT"),
        new BrokersStockEntry("SE0000886897", "MNW Records Group AB,MNW"),
        new BrokersStockEntry("SE0000941106", "MNW RECORDS TR (NGM) (A0206),MNW TR"),
        new BrokersStockEntry("3598", "Modern Times Group MTG AB ser. A,MTG A"),
        new BrokersStockEntry("3599", "Modern Times Group MTG AB ser. B,MTG B"),
        new BrokersStockEntry("1021", "Modul 1 Data AB,MOD1"),
        new BrokersStockEntry("5368", "Mogul AB,MOGL"),
        new BrokersStockEntry("SE0000235574", "Monark Stiga AB,MOST"),
        new BrokersStockEntry("SE0001047929", "MORPHIC T TRB (NOTC) (A0304),MOTR OTC"),
        new BrokersStockEntry("SE0001047937", "MORPHIC TECH BTB (NOTC) (A0304),MOBT OTC"),
        new BrokersStockEntry("SE0000673980", "MORPHIC TO2 (SIX) (A0202),MORP TO2"),
        new BrokersStockEntry("1023", "MSC Konsult AB ser. B,MSC B"),
        new BrokersStockEntry("1024", "MTV Produktion AB ser. B,MTVP B"),
        new BrokersStockEntry("4359", "MultiQ International AB,MULQ"),
        new BrokersStockEntry("SE0000514507", "Multisimplex AB ser. B"),
        new BrokersStockEntry("1025", "Munters AB,MTRS"),
        new BrokersStockEntry("SE0000672024", "Music Bay AB"),
        new BrokersStockEntry("24774", "Nanook Investment AB,NANO"),
        new BrokersStockEntry("SE0000538845", "Naturkompaniet AB,NATK"),
        new BrokersStockEntry("837", "NCC AB ser. A,NCC A"),
        new BrokersStockEntry("838", "NCC AB ser. B,NCC B"),
        new BrokersStockEntry("919", "Nefab AB ser. B,NEF B"),
        new BrokersStockEntry("11165", "NeoNet AB,NEO"),
        new BrokersStockEntry("24123", "NEONET UR 2004,NEO UR"),
        new BrokersStockEntry("SE0000594038", "Net Capital AB ser. B,NCAP B"),
        new BrokersStockEntry("3871", "Net Insight AB ser. B,NETI B"),
        new BrokersStockEntry("19034", "NET INSIGHT BTB (A0207),NETI BTB"),
        new BrokersStockEntry("19034", "NET INSIGHT BTB (A0307),NETI BTB"),
        new BrokersStockEntry("21925", "NET INSIGHT IAB (A0312),NETI IAB"),
        new BrokersStockEntry("19033", "NET INSIGHT TRB (A0206),NETI TRB"),
        new BrokersStockEntry("19033", "NET INSIGHT TRB (A0306),NETI TRB"),
        new BrokersStockEntry("4743", "Netrevelation Holding AB,NETR"),
        new BrokersStockEntry("21935", "NETREVELATION UR 2003,NETR UR"),
        new BrokersStockEntry("25084", "Nettonet AB,NON"),
        new BrokersStockEntry("21184", "Netwise AB ser. B,NETW B"),
        new BrokersStockEntry("24914", "NEW WAVE GR. BTB (A0407),NEWA BTB"),
        new BrokersStockEntry("24913", "NEW WAVE GR. TRB 2004,NEWA TRB"),
        new BrokersStockEntry("920", "New Wave Group AB ser. B,NEWA B"),
        new BrokersStockEntry("SE0001200262", "NEXTLINK BT (NOTC) (A0407),NXTL OTC BT"),
        new BrokersStockEntry("SE0000995086", "NFO DR. KV (NOTC) (A0309),NFKV OTC"),
        new BrokersStockEntry("SE0000995078", "NFO DR. TO (NOTC) (A0309),NFTO OTC"),
        new BrokersStockEntry("SE0000996126", "NFO DR. UR (SIX) (A0210),NFO UR"),
        new BrokersStockEntry("SE0001094046", "NFO DRIVES TRB (NOTC) (A0309),NFO OTC TRB"),
        new BrokersStockEntry("921", "NIBE Industrier AB ser. B,NIBE B"),
        new BrokersStockEntry("922", "Nilörngruppen AB ser. B,NILG B"),
        new BrokersStockEntry("SE0000226367", "Nobel Biocare AB,NOBE"),
        new BrokersStockEntry("19175", "Nobel Biocare Holding AG,NOBE"),
        new BrokersStockEntry("19095", "Nobia AB,NOBI"),
        new BrokersStockEntry("2346", "NOCOM AB ser. B,NOCM B"),
        new BrokersStockEntry("200", "Nokia Abp, SDB,NOKI"),
        new BrokersStockEntry("923", "Nolato AB ser. B,NOLA B"),
        new BrokersStockEntry("18359", "NOLATO TR B (A0205),NOLA TRB"),
        new BrokersStockEntry("220", "Nordea Bank AB,NDA SEK"),
        new BrokersStockEntry("4124", "Nordea Bank AB EUR,NDA E"),
        new BrokersStockEntry("21171", "NORDIC SHOES BTB (A0306),NSA BTB"),
        new BrokersStockEntry("21168", "NORDIC SHOES TRB,NSA TRB"),
        new BrokersStockEntry("SE0000239733", "Nordifagruppen AB ser. A,NOFA A"),
        new BrokersStockEntry("SE0000239741", "Nordifagruppen AB ser. B,NOFA B"),
        new BrokersStockEntry("SE0000371338", "NordiTube Technologies AB"),
        new BrokersStockEntry("4872", "Nordnet AB ser. B,NN B"),
        new BrokersStockEntry("SE0000350696", "Norrporten, Fastighetsab,NORP"),
        new BrokersStockEntry("870", "Norsk Hydro ASA SDB,HYDR"),
        new BrokersStockEntry("1029", "North Atlantic Natural Resources AB,NAN"),
        new BrokersStockEntry("25319", "NOTE AB,NOTE"),
        new BrokersStockEntry("SE0000507774", "Novada AB,NOVA"),
        new BrokersStockEntry("22251", "NOVESTRA BT (A0310),NOVE BT"),
        new BrokersStockEntry("22250", "NOVESTRA TR 2003,NOVE TR"),
        new BrokersStockEntry("5116", "Novestra, AB,NOVE"),
        new BrokersStockEntry("4000", "NOVOTEK AB ser. B,NTEK B"),
        new BrokersStockEntry("SE0000469132", "NovyRost Investment Ltd"),
        new BrokersStockEntry("926", "Närkes Elektriska AB ser. B,NEA B"),
        new BrokersStockEntry("SE0001023904", "OBDUCAT BTB (A0303),OBDU BTB"),
        new BrokersStockEntry("SE0000880833", "OBDUCAT BTB (NGM) (A0203)"),
        new BrokersStockEntry("SE0000918849", "OBDUCAT IAB (NGM) (A0305),OBDU IAB"),
        new BrokersStockEntry("SE0000795254", "OBDUCAT KVB (NGM) (A0403),OBDU KVB"),
        new BrokersStockEntry("SE0001023896", "OBDUCAT TRB (NGM) (A0301),OBDU TRB"),
        new BrokersStockEntry("1056", "Observer AB,OBS"),
        new BrokersStockEntry("SE0000381782", "Observer AB ser. A,OBS A"),
        new BrokersStockEntry("SE0000381790", "Observer AB ser. B,OBS B"),
        new BrokersStockEntry("18112", "OBSERVER TR (A0204),OBS TR"),
        new BrokersStockEntry("CH0011449078", "Obtech Medical AG"),
        new BrokersStockEntry("SE0000909772", "ODEN UR (TORGET) (A0203),ODEN UR"),
        new BrokersStockEntry("927", "OEM International AB ser. B,OEM B"),
        new BrokersStockEntry("405", "OM HEX AB,OMH"),
        new BrokersStockEntry("1007", "onetwocom AB,O2C"),
        new BrokersStockEntry("2282", "Opcon AB,OPCO"),
        new BrokersStockEntry("968", "Optimail AB ser. A,OPTI A"),
        new BrokersStockEntry("SE0000481079", "Optimum Optik AB ser. B,OPT B"),
        new BrokersStockEntry("SE0001134339", "OPTOVENT TRB 2003,OPVE TRB"),
        new BrokersStockEntry("11160", "Orc Software AB,ORC"),
        new BrokersStockEntry("24227", "Oriflame Cosmetics S.A, SDB,ORI"),
        new BrokersStockEntry("1031", "Ortivus AB ser. A,ORTI A"),
        new BrokersStockEntry("1032", "Ortivus AB ser. B,ORTI B"),
        new BrokersStockEntry("1033", "Oxigene, Inc.,OXGN"),
        new BrokersStockEntry("1034", "Pandox AB,PAND"),
        new BrokersStockEntry("1036", "PartnerTech AB,PART"),
        new BrokersStockEntry("928", "Peab AB ser. B,PEAB B"),
        new BrokersStockEntry("4228", "Perbio Science AB,PBIO"),
        new BrokersStockEntry("13424", "Pergo AB,PERG"),
        new BrokersStockEntry("17316", "PERGO TR (A0202),PERG TR"),
        new BrokersStockEntry("4984", "Persea AB ser. B,PSEA B"),
        new BrokersStockEntry("SE0000110710", "Perstorp AB ser. A,PERS A"),
        new BrokersStockEntry("SE0000110736", "Perstorp AB ser. B,PERS B"),
        new BrokersStockEntry("21227", "Pfizer Inc.,PFE"),
        new BrokersStockEntry("SE0000289928", "Pharmacia &amp; Upjohn, Inc. SDB,PHU"),
        new BrokersStockEntry("SE0000634040", "Pharmacia Corporation SDB,PHA"),
        new BrokersStockEntry("SE0000204828", "Piren AB,PIRE"),
        new BrokersStockEntry("SE0000110959", "Platzer Fastigheter AB ser. B,PLAT B"),
        new BrokersStockEntry("3974", "Poolia AB ser. B,POOL B"),
        new BrokersStockEntry("21693", "POOLIA ILB (A0310),POOL ILB"),
        new BrokersStockEntry("21422", "POOLIA SR1,POOL SR1"),
        new BrokersStockEntry("5113", "Powerit PS AB,POWI"),
        new BrokersStockEntry("24640", "POWERIT PS BT (NYAM) (A0406),POWI BT"),
        new BrokersStockEntry("24637", "POWERIT PS TR 04 (NYAM),POWI TR"),
        new BrokersStockEntry("25224", "Powerwave Technologies Inc,PWAV"),
        new BrokersStockEntry("20108", "PRECISE BIOM BTA (A0301),PREC BTA"),
        new BrokersStockEntry("20108", "PRECISE BIOM BTA (A0307),PREC BTA"),
        new BrokersStockEntry("20108", "PRECISE BIOM BTA (A0404),PREC BTA"),
        new BrokersStockEntry("20106", "PRECISE BIOM TRA (A0212),PREC TRA"),
        new BrokersStockEntry("20106", "PRECISE BIOM TRA (A0306),PREC TRA"),
        new BrokersStockEntry("10751", "Precise Biometrics AB ser. A,PREC A"),
        new BrokersStockEntry("1039", "Prevas AB ser. B,PREV B"),
        new BrokersStockEntry("1040", "Pricer AB ser. B,PRIC B"),
        new BrokersStockEntry("23047", "PRICER BTU 2003,PRIC BTU"),
        new BrokersStockEntry("17804", "PRICER TR B (A0203),PRIC TRB"),
        new BrokersStockEntry("23046", "PRICER URB 2003,PRIC URB"),
        new BrokersStockEntry("4003", "Proact IT Group AB,PACT"),
        new BrokersStockEntry("13222", "PROACT TR (A0106),PACT TR"),
        new BrokersStockEntry("4208", "Proffice AB ser. B,PROE B"),
        new BrokersStockEntry("929", "ProfilGruppen AB ser. B,PROF B"),
        new BrokersStockEntry("SE0000374704", "Pronyx AB,PRYX"),
        new BrokersStockEntry("18075", "PRONYX TRV 2002,PRYX TRV"),
        new BrokersStockEntry("SE0000969271", "PROSOLUT. TR (NGM) (A0208),PRSO TR"),
        new BrokersStockEntry("SE0000969289", "Prosolutions AB BT,PRSO BT"),
        new BrokersStockEntry("1035", "Protect Data AB,PROT"),
        new BrokersStockEntry("SE0000240772", "Provobis Hotel &amp; Restauranger AB ser. B,PHOT B"),
        new BrokersStockEntry("SE0000430894", "Pure Water Technology AB"),
        new BrokersStockEntry("FI0009006696", "Pöyry Group Oyj, Jaakko,JAP"),
        new BrokersStockEntry("4354", "Q-Med AB,QMED"),
        new BrokersStockEntry("1044", "Ratos AB ser. A,RATO A"),
        new BrokersStockEntry("1045", "Ratos AB ser. B,RATO B"),
        new BrokersStockEntry("1063", "RaySearch Laboratories AB ser. B,RAY B"),
        new BrokersStockEntry("3967", "ReadSoft AB ser. B,RSOF B"),
        new BrokersStockEntry("SE0000191298", "Realia AB ser. A,REAL A"),
        new BrokersStockEntry("SE0000193286", "Realia AB ser. B,REAL B"),
        new BrokersStockEntry("DK0010158773", "REGIONAL INVEST (A0204),RegInv.Fyn"),
        new BrokersStockEntry("5367", "Reguard AB,REGU"),
        new BrokersStockEntry("SE0000795411", "Rene Wable Energy in Sweden AB,RNEW"),
        new BrokersStockEntry("1048", "Resco AB ser. B,RESC B"),
        new BrokersStockEntry("SE0000373473", "Riddarhyttan Resources AB,RHYT"),
        new BrokersStockEntry("4871", "Riddarhyttan Resources AB,RHYT"),
        new BrokersStockEntry("14655", "RIDDARHYTTAN TR (A0110),RHYT TR"),
        new BrokersStockEntry("SE0000581290", "Rindi Energi AB ser. B"),
        new BrokersStockEntry("3643", "RKS AB ser. B,RKS B"),
        new BrokersStockEntry("21365", "RKS BTB (A0307),RKS BTB"),
        new BrokersStockEntry("21364", "RKS TRB (A0306),RKS TRB"),
        new BrokersStockEntry("13467", "rnb Retail and Brands AB,RNBS"),
        new BrokersStockEntry("930", "Rottneros AB,RROS"),
        new BrokersStockEntry("1050", "Rörvik Timber AB ser. B,RTIM B"),
        new BrokersStockEntry("1051", "SAAB AB ser. B,SAAB B"),
        new BrokersStockEntry("SE0000147555", "Saint-Gobain, Compagnie de SDB,SAGO"),
        new BrokersStockEntry("1053", "SalusAnsvar AB ser. B,SALA B"),
        new BrokersStockEntry("DK0010160837", "SAMSON GROUP (A0306),Samson T."),
        new BrokersStockEntry("4928", "Sandvik AB,SAND"),
        new BrokersStockEntry("985", "Sapa AB,SAPA"),
        new BrokersStockEntry("848", "Sardus, AB,SARD"),
        new BrokersStockEntry("13557", "SAS AB,SAS"),
        new BrokersStockEntry("SE0000329146", "SAS Sverige AB,USAS"),
        new BrokersStockEntry("SE0000518425", "Satsafe MLS AB"),
        new BrokersStockEntry("SE0001097577", "SBT BTB (NGM) (A0401),SBTL BTB"),
        new BrokersStockEntry("SE0000938417", "SBT TRB (NGM) (A0206)"),
        new BrokersStockEntry("SE0001097569", "SBT TRB (NGM) (A0309),SBTL TRB"),
        new BrokersStockEntry("15282", "SCAN MINING TR (A0112),SCMI TR"),
        new BrokersStockEntry("SE0000120859", "Scandiaconsult AB,SCC"),
        new BrokersStockEntry("SE0000351157", "Scandic Hotels AB,SHOT"),
        new BrokersStockEntry("SE0000673907", "Scandinavia Online AB,SCOL"),
        new BrokersStockEntry("260", "SCANIA AB ser. A,SCV A"),
        new BrokersStockEntry("261", "SCANIA AB ser. B,SCV B"),
        new BrokersStockEntry("3819", "ScanMining  AB,SCMI"),
        new BrokersStockEntry("22801", "SCANMINING BTU (A0312),SCMI BTU"),
        new BrokersStockEntry("22800", "SCANMINING UR 2003,SCMI UR"),
        new BrokersStockEntry("854", "Scribona AB ser. A,SCRI A"),
        new BrokersStockEntry("855", "Scribona AB ser. B,SCRI B"),
        new BrokersStockEntry("SE0000590630", "Sea Power International AB"),
        new BrokersStockEntry("856", "Seco Tools AB ser. B,SECO B"),
        new BrokersStockEntry("3083", "SECTRA AB ser B,SECT B"),
        new BrokersStockEntry("401", "Securitas AB ser. B,SECU B"),
        new BrokersStockEntry("1054", "Semcon AB,SEMC"),
        new BrokersStockEntry("933", "Senea AB ser. A,SENE A"),
        new BrokersStockEntry("SE0001093360", "Senea AB Teckningsoption 1A,SENE TO1A"),
        new BrokersStockEntry("14872", "SENEA BT (A0211),SENE BT"),
        new BrokersStockEntry("14872", "SENEA BT (A0307),SENE BT"),
        new BrokersStockEntry("24843", "SENEA BTA (A0407),SENE BTA"),
        new BrokersStockEntry("14871", "SENEA TR (A0210),SENE TR"),
        new BrokersStockEntry("14871", "SENEA TR (A0306),SENE TR"),
        new BrokersStockEntry("24842", "SENEA TRA 2004,SENE TRA"),
        new BrokersStockEntry("12241", "Sensys Traffic AB,SENS"),
        new BrokersStockEntry("17272", "SENSYS TRAFFIC UR 2002,SENS UR"),
        new BrokersStockEntry("14531", "Sigma AB ser. B,SIGM B"),
        new BrokersStockEntry("21256", "SIGMA BTB (A0306),SIGM BTB"),
        new BrokersStockEntry("21255", "SIGMA TRB,SIGM TRB"),
        new BrokersStockEntry("21759", "SIGN ON BT (A0309),SION BT"),
        new BrokersStockEntry("19210", "Sign On i Stockholm AB,SION"),
        new BrokersStockEntry("21758", "SIGN ON TR,SION TR"),
        new BrokersStockEntry("18608", "SIGN ON TR (NYAM) (A0205),SION TR"),
        new BrokersStockEntry("1058", "SinterCast AB,SINT"),
        new BrokersStockEntry("SE0000166506", "SinterCast AB ser. A,SINT A"),
        new BrokersStockEntry("SE0000166514", "SinterCast AB ser. B,SINT B"),
        new BrokersStockEntry("DK0010170042", "SKAKO (A0307)"),
        new BrokersStockEntry("280", "Skandia Försäkringsab,SDIA SEK"),
        new BrokersStockEntry("281", "Skandinaviska Enskilda Banken ser. A,SEB A"),
        new BrokersStockEntry("282", "Skandinaviska Enskilda Banken ser. C,SEB C"),
        new BrokersStockEntry("1060", "Skanditek Industriförvaltning AB.,STEK"),
        new BrokersStockEntry("283", "Skanska AB ser. B,SKA B"),
        new BrokersStockEntry("284", "SKF, AB ser. A,SKF A"),
        new BrokersStockEntry("285", "SKF, AB ser. B,SKF B"),
        new BrokersStockEntry("939", "SkiStar AB ser. B,SKIS B"),
        new BrokersStockEntry("SE0000571275", "SKRIBO FONT B (A0207),SKRI B"),
        new BrokersStockEntry("SE0000542896", "Skultuna Messingsbruk AB"),
        new BrokersStockEntry("SE0000630154", "Sky Ventures AB,SKY"),
        new BrokersStockEntry("24912", "SKYCOM BT (TORGET) (A0407),SKYC BT"),
        new BrokersStockEntry("24911", "SKYCOM TR (TORGET) (A0405),SKYC TR"),
        new BrokersStockEntry("1452", "Skåne-möllan AB,SKMO"),
        new BrokersStockEntry("SE0000984981", "SMARTEQ TRB (NGM) (A0209),SMAQ TRB"),
        new BrokersStockEntry("SE0001051764", "Smurfit Munksj÷ AB,MUNK"),
        new BrokersStockEntry("SE0000749988", "Snapcat AB Bet. Teckn. aktier"),
        new BrokersStockEntry("SE0000478059", "Société Euro. de Communication, SDB A,SEC A"),
        new BrokersStockEntry("SE0000478067", "Société Euro. de Communication, SDB B,SEC B"),
        new BrokersStockEntry("SE0000454886", "Sodra Petroleum AB,SODR"),
        new BrokersStockEntry("1546", "Softronic AB ser. B,SOF B"),
        new BrokersStockEntry("14525", "SOFTRONIC TR B (A0110),SOF TRB"),
        new BrokersStockEntry("4750", "Song Networks Holding AB,SONW"),
        new BrokersStockEntry("23243", "South Atlantic Ventures Ltd. SDB,SAVS"),
        new BrokersStockEntry("NO0003057200", "SPCS-Gruppen ASA,SPCS ASA"),
        new BrokersStockEntry("SE0000113516", "Spendrups Bryggeriab. ser. B,SPEN B"),
        new BrokersStockEntry("SE0000427536", "Spray Ventures,SPRY"),
        new BrokersStockEntry("SE0001061037", "SRAB HOLD BTB (NGM) (A0306)"),
        new BrokersStockEntry("SE0000588063", "SRAB Holding AV KVB"),
        new BrokersStockEntry("300", "SSAB Svenskt Stål AB ser. A,SSAB A"),
        new BrokersStockEntry("301", "SSAB Svenskt Stål AB ser. B,SSAB B"),
        new BrokersStockEntry("SE0001061300", "STARBREEZE TR (A0304)"),
        new BrokersStockEntry("SE0000116949", "Stena Line AB ser. B,SLAB B"),
        new BrokersStockEntry("SE0001183617", "STILLE BT (NGM) (A0406),STIL BT"),
        new BrokersStockEntry("2169", "Stora Enso Oyj ser. A,STE A"),
        new BrokersStockEntry("3526", "Stora Enso Oyj ser. AE,STE AE"),
        new BrokersStockEntry("2170", "Stora Enso Oyj ser. R,STE R"),
        new BrokersStockEntry("3527", "Stora Enso Oyj ser. RE,STE RE"),
        new BrokersStockEntry("934", "Strålfors AB ser. B,STRA B"),
        new BrokersStockEntry("13094", "Studsvik AB,SVIK"),
        new BrokersStockEntry("SE0001027632", "SV. FAST. FOND KV (NGM) (A0403),SVFF KV"),
        new BrokersStockEntry("SE0001016973", "Sveaskog Förvaltnings AB,SVEA OTC"),
        new BrokersStockEntry("1061", "SWECO AB ser. A,SWEC A"),
        new BrokersStockEntry("1062", "SWECO AB ser. B,SWEC B"),
        new BrokersStockEntry("SE0000108169", "Svedala Industri AB,SVDA"),
        new BrokersStockEntry("935", "Svedbergs i Dalstorp AB ser. B,SVED B"),
        new BrokersStockEntry("361", "Swedish Match AB,SWMA"),
        new BrokersStockEntry("SE0000498602", "Svensk Fastighetsfond AB,SVFF"),
        new BrokersStockEntry("322", "Svenska Cellulosa AB SCA ser. A,SCA A"),
        new BrokersStockEntry("323", "Svenska Cellulosa AB SCA ser. B,SCA B"),
        new BrokersStockEntry("340", "Svenska Handelsbanken ser. A,SHB A"),
        new BrokersStockEntry("341", "Svenska Handelsbanken ser. B,SHB B"),
        new BrokersStockEntry("SE0000841447", "Svenska Kaolin AB,KLIN"),
        new BrokersStockEntry("SE0000416125", "Svenska Orient Linien AB ser. B,SOL B"),
        new BrokersStockEntry("4353", "SwitchCore AB,SCOR"),
        new BrokersStockEntry("21254", "SWITCHCORE BT (A0306),SCOR BT"),
        new BrokersStockEntry("13231", "SWITCHCORE TR (A0106),SCOR TR"),
        new BrokersStockEntry("21253", "SWITCHCORE TR 03,SCOR TR"),
        new BrokersStockEntry("936", "Svolder AB ser. A,SVOL A"),
        new BrokersStockEntry("937", "Svolder AB ser. B,SVOL B"),
        new BrokersStockEntry("SE0000114431", "Sydkraft AB ser. A,SYD A"),
        new BrokersStockEntry("SE0000114456", "Sydkraft AB ser. C,SYD C"),
        new BrokersStockEntry("11238", "Syngenta AG,SYN"),
        new BrokersStockEntry("SE0000909947", "Syrico AB,SYRI"),
        new BrokersStockEntry("938", "SäkI AB,SAEK"),
        new BrokersStockEntry("20793", "särskilda rätter i IFS AB,IFS SR1"),
        new BrokersStockEntry("SE0000514408", "TagMaster AB ser. B"),
        new BrokersStockEntry("23234", "Tanganyika Oil Company Ltd. SDB,TYKS"),
        new BrokersStockEntry("SE0000402034", "TARGET INV. (NGM) (A0206),TARG B"),
        new BrokersStockEntry("SE0000932626", "TARGET INV. TRB (NGM) (A0205),TARG TRB"),
        new BrokersStockEntry("1826", "Technology Nexus AB,NEXU"),
        new BrokersStockEntry("12746", "teckningsrätter ser. B i Getinge Industrier AB,GIND TRB"),
        new BrokersStockEntry("1026", "Tele2 AB ser. A,TEL2 A"),
        new BrokersStockEntry("1027", "Tele2 AB ser. B,TEL2 B"),
        new BrokersStockEntry("1057", "Teleca AB ser. B,TELC B"),
        new BrokersStockEntry("3142", "Telelogic AB,TLOG"),
        new BrokersStockEntry("14251", "TELELOGIC BT (A0109),TLOG BT"),
        new BrokersStockEntry("14249", "TELELOGIC TR (A0109),TLOG TR"),
        new BrokersStockEntry("5095", "TeliaSonera AB,TLSN"),
        new BrokersStockEntry("3539", "Teligent AB,TGNT"),
        new BrokersStockEntry("21436", "TELIGENT IL (A0309),TGNT IL"),
        new BrokersStockEntry("21149", "TELIGENT SR1 (A0305),TGNT SR1"),
        new BrokersStockEntry("SE0000333333", "Testbolag_5 AB"),
        new BrokersStockEntry("24588", "Tethys Oil AB,TETY"),
        new BrokersStockEntry("5364", "Thalamus Networks AB ser. B,THAL B"),
        new BrokersStockEntry("5235", "The Empire AB ser. B,EMP B"),
        new BrokersStockEntry("1064", "Ticket Travel Group AB,TICK"),
        new BrokersStockEntry("4025", "TietoEnator Abp,TIEN"),
        new BrokersStockEntry("940", "Tivox AB ser. B,TIVO B"),
        new BrokersStockEntry("25326", "TIVOX TRB 2004,TIVO TRB"),
        new BrokersStockEntry("14935", "TMT ONE SR1 (A0112),TMT1 SR1"),
        new BrokersStockEntry("1065", "Tornet, Fastighets AB,TORN"),
        new BrokersStockEntry("SE0000564155", "TPC Security AB,TPC"),
        new BrokersStockEntry("SE0000674475", "TPC Security AB BT,TPC BT"),
        new BrokersStockEntry("SE0000674467", "TPC Security AB TR,TPC TR"),
        new BrokersStockEntry("4963", "Traction AB ser. B,TRAC B"),
        new BrokersStockEntry("14353", "Transcom WorldWide S.A SDB ser. A,TWW A"),
        new BrokersStockEntry("14354", "Transcom WorldWide S.A SDB ser. B,TWW B"),
        new BrokersStockEntry("364", "Trelleborg AB ser. B,TREL B"),
        new BrokersStockEntry("1066", "Tricorona AB.ser. B,TRIC B"),
        new BrokersStockEntry("21897", "TRICORONA BTU (A0311),TRIM BTU"),
        new BrokersStockEntry("14532", "TRICORONA SR2 (A0110),TRIM SR2"),
        new BrokersStockEntry("21896", "TRICORONA UR (A0311),TRIM UR"),
        new BrokersStockEntry("1606", "Trio AB,TRIO"),
        new BrokersStockEntry("5256", "Tripep AB,TPEP"),
        new BrokersStockEntry("21099", "TRIPEP SR,TPEP SR"),
        new BrokersStockEntry("SE0000166555", "Trustor AB ser. B,TRUS B"),
        new BrokersStockEntry("SE0000684664", "Turkronan AB:s akt. ser. B,TURK B"),
        new BrokersStockEntry("1067", "TurnIT AB ser. B,TURN B"),
        new BrokersStockEntry("3039", "TURNIT TRB 2004,TURN TRB"),
        new BrokersStockEntry("860", "TV4 AB ser. A,TV4 A"),
        new BrokersStockEntry("25232", "Unibet Group Plc, SDB,UNIB"),
        new BrokersStockEntry("20807", "unit rätter i Modul 1 Data AB,MOD1 UR"),
        new BrokersStockEntry("4877", "Utfors AB,UTFO"),
        new BrokersStockEntry("15995", "UTFORS TR (A0201),UTFO TR"),
        new BrokersStockEntry("945", "Wallenstam Byggnads AB., Lennart ser. B,WALL B"),
        new BrokersStockEntry("942", "VBG AB ser. B,VBG B"),
        new BrokersStockEntry("946", "Wedins Skor &amp; Accessoarer AB ser. B,WED B"),
        new BrokersStockEntry("11746", "West Siberian Resources Ltd.,WSIB"),
        new BrokersStockEntry("947", "Westergyllen, AB ser. B,WEST B"),
        new BrokersStockEntry("11222", "WIHLBORG IA B (A0011),WIHL IAB"),
        new BrokersStockEntry("861", "Wihlborgs Fastigheter AB,WIHL"),
        new BrokersStockEntry("SE0000115354", "Wihlborgs Fastigheter AB ser. B,WIHL B"),
        new BrokersStockEntry("5000", "Viking Telecom AB,VIKT"),
        new BrokersStockEntry("3921", "Wilh. Sonesson AB ser. A,WSON A"),
        new BrokersStockEntry("3922", "Wilh. Sonesson AB ser. B,WSON B"),
        new BrokersStockEntry("SE0000502312", "Virtual Genetics Laboratory AB,VIGE"),
        new BrokersStockEntry("SE0000640369", "Vision Park Entertainment AB,VPE"),
        new BrokersStockEntry("13469", "Vitrolife AB,VITR"),
        new BrokersStockEntry("944", "VLT AB ser. B,VLT B"),
        new BrokersStockEntry("406", "WM-data AB ser. B,WM B"),
        new BrokersStockEntry("365", "Volvo, AB ser. A,VOLV A"),
        new BrokersStockEntry("366", "Volvo, AB ser. B,VOLV B"),
        new BrokersStockEntry("18606", "VOST OIL TRV (NYAM) (A0205),VOIL TRV"),
        new BrokersStockEntry("SE0000901779", "Vostok Energo Investment Ltd,ENRG"),
        new BrokersStockEntry("SE0000901803", "Vostok Energo Investment Ltd IR,ENRG IR"),
        new BrokersStockEntry("17948", "VOSTOK ENERGO TO1 (A0301),ENRG TO1"),
        new BrokersStockEntry("1068", "Vostok Nafta, Inv Ltd SDB,VOST"),
        new BrokersStockEntry("SE0000739294", "Vostok Oil Ltd IR,VOIL IR"),
        new BrokersStockEntry("984", "XponCard Group AB,XPON"),
        new BrokersStockEntry("SE0001100553", "XYLOGEN (NOTC) (A0405)"),
        new BrokersStockEntry("SE0000514325", "ZAPP AB ser. B,ZAPP B"),
        new BrokersStockEntry("SE0000115503", "ZETECO AB ser. B,ZETE B"),
        new BrokersStockEntry("SE0000524811", "Åhus Glass AB,AHUS B"),
        new BrokersStockEntry("862", "Ångpanneföreningen, AB ser. B,ANGP B"),
        new BrokersStockEntry("863", "Öresund, Investmentab,ORES")
    };

    public void init(WebAppEnvironmentInterface environment) {
        this.environment = environment;
    }
    public String getStock(String fondPrefix) {
        try {
            //URL url =new URL("http://p233/StockServlet?do=login&name=erland&password=dnalre");
            //URL url = new URL("http://www.google.com/search?q=erland");
            //URL url =new URL("http://www.stockholmsborsen.se/stocklist.asp?lang=swe&list=SSE43&group=Kursnoteringar&listName=O-listan, samtliga");
            //URL url = new URL("http://www.stockholmsborsen.se/getHistory.asp?isin=SE0000105116");
            URL url = new URL("http://www.stockholmsborsen.se/Slutkurser/excel.asp?"+
                    "InstrumentID="+fondPrefix+
                    "&InstrumentType=1"+
                    "&From=1980-01-01"+
                    "&todate=2005-01-01");
            URLConnection conn = url.openConnection();
            conn.setDoInput(true);
            conn.setDoOutput(false);
            conn.setUseCaches(false);


            String s = System.getProperty("http.agent", "Unknown/1.0");
            String s1 = System.getProperty("os.arch", "") + " [" + Locale.getDefault().getLanguage() + "] " + System.getProperty("os.name", "") + " " + System.getProperty("os.version", "") + "; Sun";
            s = s + " (" + s1 + ")";
            Log.println(this,s);
            conn.setRequestProperty("User-Agent", s);
            conn.setRequestProperty("Content-Type","application/x-www-form-urlencoded");
            BufferedReader inSB = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            /*
            String line;
            while((line = inSB.readLine())!=null) {
                System.out.println(line);
            }
            */
            String result = SBXMLEncoder.encodeStockData(inSB);
            Log.println(this,result,Log.DEBUG);
            inSB.close();
            return result;
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public BrokersStockEntry[] getAvailableStocks() {
        return availableStocks;
    }

    public String getName() {
        return environment.getResources().getParameter("brokers.sb.name");
    }
    /*
    public static void main(String[] args) {
        //Log.setLog(true);
        XMLParser.setInstance(new SAXXMLParser());
        String result = new SBConnection().getStock(args[0]);
        System.out.println("result = " + result);
    }
    */
}
