package erland.webapp.stocks.sb;

import erland.webapp.stocks.BrokerConnectionInterface;
import erland.webapp.stocks.BrokersStockEntry;
import erland.webapp.common.WebAppEnvironmentInterface;

import java.net.URL;
import java.net.URLConnection;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Locale;
import java.util.Vector;
import java.util.Iterator;

public class SBConnection implements BrokerConnectionInterface {
    private final static Vector availableStocks = new Vector();
    private WebAppEnvironmentInterface environment;

    static {
        availableStocks.removeAllElements();
        availableStocks.addElement(new BrokersStockEntry("SE0000524811","+hus Glass AB,AHUS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000680902","2Entertain AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000494072","3L Systems AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000449068","A Brand New World in Sweden  AB ser. B,ABNW B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000750010","A Brand New World in Sweden AB BT ser. B,ABNW BTB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000750002","A Brand New World in Sweden AB TR ser. B,ABNW TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000490195","AAU Aktiv IT AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("CH0012221716","ABB Ltd,ABB"));
        availableStocks.addElement(new BrokersStockEntry("CH0003846620","ABB Ltd,ABB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000625568","ABB Ltd ser. U,ABB U"));
        availableStocks.addElement(new BrokersStockEntry("SE0000375545","AcadeMedia AB ser. B,ACAD B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000592677","A-Com AB,ACOM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000100026","Active Biotech AB ser. A,ACTI A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000100042","Active Biotech AB ser. B,ACTI B"));
        availableStocks.addElement(new BrokersStockEntry("19074","Active Capital AB ser A IR,ACAP IRA"));
        availableStocks.addElement(new BrokersStockEntry("19079","Active Capital AB ser B IR,ACAP IRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000937674","Active Capital AB ser. A,ACAP A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000937682","Active Capital AB ser. B,ACAP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000331225","Adcore AB,ADCO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000808370","Addtech AB ser. B,ADDT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000442121","addVise Inredning Skyddsvent. AB ser. B,ADDV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000472268","Adera AB ser. B,ADER B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000739013","Aerodyn AB,HOLM1P"));
        availableStocks.addElement(new BrokersStockEntry("SE0000445934","Affärsstrategerna AB ser. B,AFFS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000645954","Airbite AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000227258","Akzo Nobel N. V. SDB,AKZO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000147480","Alcatel Alsthom Comp. Gen dÉ,ALCA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000695876","Alfa Laval AB,ALFA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000364283","Alfaskop AB,ALFA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000459323","All Cards Service Center - ACSC AB,ACSC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000100364","Allgon AB ser. B,ALLG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000547929","Anoto Group AB,ANOT"));
        availableStocks.addElement(new BrokersStockEntry("19828","Anoto Group AB TR,ANOT TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000682205","aPROch AB,APRO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000542128","Aqua Terrena International AB,ATI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000431058","Arcam AB ser. B, "));
        availableStocks.addElement(new BrokersStockEntry("SE0000429706","ARETE AB,ARET"));
        availableStocks.addElement(new BrokersStockEntry("SE0000442907","ARK Travel AB,ARKT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000772956","Aros Quality Group AB,AQ"));
        availableStocks.addElement(new BrokersStockEntry("SE0000237398","Array AB ser. B,ARRA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000275943","Artema Medical AB ser. B,ARTM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000477192","Artika AB,ATMG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000413221","Artimplant AB ser. B,ARTI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000500258","Aspiro AB,ASP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000695454","Aspiro AB BT,ASP BT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000695447","Aspiro AB TR,ASP TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000255648","ASSA ABLOY AB ser. B,ASSA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000230963","AssiDomän AB,ASDO"));
        availableStocks.addElement(new BrokersStockEntry("GB0009895292","AstraZeneca PLC,AZN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101032","Atlas Copco AB ser. A,ATCO A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000122467","Atlas Copco AB ser. B,ATCO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000195802","Atle AB,ATLE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000708620","AudioDev AB ser B,AUDV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000349821","Aurex AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000674509","AU-System AB,AUS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000579591","Autofill AB,AFIL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000382335","Autoliv Inc. SDB,ALIV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000170110","Avanza AB,AZA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101047","Avesta Sheffield,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101057","Avesta Sheffield AB,AVES"));
        availableStocks.addElement(new BrokersStockEntry("SE0000899874","Avesta Sheffield AB Tvsngsinl÷senaktie,null"));
        availableStocks.addElement(new BrokersStockEntry("NULL","AvestaPolarit Abp,AVPO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000635401","Axfood AB,AXFO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000672354","Axis AB,AXIS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000143521","B&amp;N Nordsjöfrakt AB ser. B,BN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000469769","Balder, Fastighets AB,BALD"));
        availableStocks.addElement(new BrokersStockEntry("SE0000524191","Ballingslöv International AB,BALL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000537086","Barnfamiljen.com AB ser. B,BARN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000169070","Bayer Aktiengesellschaft,BAYE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514556","Bedminster AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000112906","Beijer AB, G &amp; L ser. B,BEIJ B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000190134","Beijer Alma AB ser. B,BEIA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000671711","Beijer Electronics AB,BELE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101297","Berg &amp; Co, AB, C F ser. B,BRG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101362","Bergman &amp; Beving AB ser. B,BERG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000353351","Biacore International AB,BCOR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102295","Bilia AB ser. A,BILI A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000862997","Billerud AB,BILL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000393720","BinSr AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000470395","BioGaia AB ser. B,BIOG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000789711","BioInvent International AB,BINV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000310682","Biolight Int. AB serie A,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000310690","Biolight Int. AB serie B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000327090","Biolin AB,BLIN"));
        availableStocks.addElement(new BrokersStockEntry("SE0001048984","BioPhausia AB,BIOP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000293656","BioPhausia AB ser. A,BIOP A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000361909","Biora AB,BIOR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000653404","BlueMarx AB,BLX"));
        availableStocks.addElement(new BrokersStockEntry("SE0000869646","Boliden AB,BOL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000558470","Boliden Limited, SDB,BOL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000396061","Bong Ljungdahl AB,BONG"));
        availableStocks.addElement(new BrokersStockEntry("18683","Bong Ljungdahl AB TR,BONG TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101891","Borås Wäfveri AB ser. B,WAFV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000488850","Boss Media AB,BOSS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000436974","Bringwell International AB,BWL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102006","BRIO AB ser. B,BRIO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000254880","Broström AB ser.B,BRO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000291171","BT Industries AB,BTI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000805426","BTS Group AB ser. B,BTS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000123267","Bulten AB ser. B,BULT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000195810","Bure Equity AB,BURE"));
        availableStocks.addElement(new BrokersStockEntry("NULL","Capinordic A/S,CAPI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000718199","Capio AB,CAP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000525057","Capona AB,CAPO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000262982","Cardo AB,CARD"));
        availableStocks.addElement(new BrokersStockEntry("DK0010221803","Carli  Gry International A/S,CGIA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000798829","Carnegie &amp; Co AB, D.,CAR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000522823","Cartesia Informationsteknik AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514440","Cash Guard AB,CASH B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000523441","Castcom AB,CCOM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000379190","Castellum AB,CAST"));
        availableStocks.addElement(new BrokersStockEntry("SE0000394470","Cell Network AB,CELL"));
        availableStocks.addElement(new BrokersStockEntry("13223","Cell Network AB TR,CELL TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000769044","CellPoint Inc, SDB,CLPT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000135303","Celtica, Fastighetsab.,CELT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000723652","Centrcourt AB BT,CENT BT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000519928","Centrecourt AB,CENT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102378","Cherryföretagen AB ser. B,CHER B"));
        availableStocks.addElement(new BrokersStockEntry("20067","Cherryföretagen AB TR ser. B,CHER TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000584948","Clas Ohlson AB ser. B,CLAS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102642","Cloetta Fazer AB ser. B,CFA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000672040","Coldator FreshCool Int. AB,COLD B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000653495","Comexchange Commercial Exchanges AB,COMX"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102824","Concordia Maritime AB ser. B,CCOR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000325839","Confidence International AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000961724","Connecta AB,CNTA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000585960","Connecta AB ser. B,CNTA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102840","Conpharm AB,CONP A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102857","Conpharm AB,CONP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000236382","Consilium AB ser. B,CONS B"));
        availableStocks.addElement(new BrokersStockEntry("13293","Consilium AB TR ser. B,CONS TRVB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514341","Countermine Technologies AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000324428","CTC Medical AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000418923","CTT Systems AB,CTT"));
        availableStocks.addElement(new BrokersStockEntry("14932","Custos AB IL,CUST IL"));
        availableStocks.addElement(new BrokersStockEntry("14679","Custos AB SR,CUST SR1"));
        availableStocks.addElement(new BrokersStockEntry("SE0000702177","Custos, AB,CUST"));
        availableStocks.addElement(new BrokersStockEntry("SE0000103046","Custos, AB ser. B,CUST B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000702169","Cyber Com Cons. Group Scand. AB,CYBE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000665937","Cycore AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000733917","Daydream Software AB BTB,DAYD BTB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000355729","Daydream Software AB ser. B,DAYD B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000733909","Daydream Software AB TRB,DAYD TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000402497","Decim AB ser. B,DECI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000750556","Decim AB TR ser. B,DECI TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000591836","Dentronic AB TR ser. B,DENT TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000384042","Dial n¦ Smile AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000410698","Dial NXT Group AB ser. B,DNG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000724809","Dial NXT Group AB ser. B BT,DIAL BTB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000724791","Dial NXT Group AB TR ser. B,DIAL TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000337917","Diamyd Medical AB ser. B,DIAM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000325870","Diffchamb AB,DIFF"));
        availableStocks.addElement(new BrokersStockEntry("SE0000436685","Digital Illusions CE AB,DICE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000556292","Digital Vision AB,DV"));
        availableStocks.addElement(new BrokersStockEntry("17848","Digital Vision AB TR,DV TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000338220","Diligentia AB,DILI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000721433","Dimension AB,DMSN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000226607","Diös AB, Anders,DIOS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000215493","DORO AB,DORO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000891798","DORO AB ser. A,DORO A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000500290","Drott AB ser. A,DROT A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000500308","Drott AB ser. B,DROT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000331266","Duroc AB ser. B,DURC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000498602","EBP Group AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000558652","Ecovision AB ser. B,ECOV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000545501","Ecta Resurs AB ser. A,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000538605","Ecta Resurs AB ser. B,ECTA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000538852","Effnet Group AB,EFFN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000718751","El &amp; Industrimontage Holding i Norrland AB,EIAB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000119299","Elanders AB ser. B,ELAN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000561623","Electrolux AB ser. BE,ELUX BE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000103806","Electrolux, AB ser. A,ELUX A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000103814","Electrolux, AB ser. B,ELUX B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000163628","Elekta AB ser. B,EKTA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000101669","ElektronikGruppen BK AB ser. B,ELGR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000912289","Elverket Vallentuna AB,ELV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000661589","Empire, The AB ser. B,EMP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514374","Enea Data AB,ENEA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000718017","Eniro AB,ENRO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000455057","Enlight AB ser. B,ENLI B"));
        availableStocks.addElement(new BrokersStockEntry("13379","Enlight AB TR ser.B,ENLI TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000538258","Entra Data AB ser. A,ENTR A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000619496","E-Play AB,EPLY"));
        availableStocks.addElement(new BrokersStockEntry("SE0000809741","Epsilon AB ser. B,EPSI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108649","Ericsson, Telefonab. L M ser. A,ERIC A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108656","Ericsson, Telefonab. L M ser. B,ERIC B"));
        availableStocks.addElement(new BrokersStockEntry("19452","Ericsson, Telefonab. L M TR ser. B,ERIC TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000104051","Esselte AB ser. A,SLT A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000104077","Esselte AB ser. B,SLT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514515","Estinvest AB,ESTI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000488744","European Institute of Science AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000237315","Europolitan Vodafone AB,EURO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110835","Evidentia Fastigheter AB ser. A,EVID A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000169195","Evidentia Fastigheter AB ser. B,EVID B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000295644","Exave AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000386138","Expanda AB ser. B,EXPA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000169435","F÷rsSkringsaktiebolaget Svenska Brand,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000568222","Facile &amp; Co AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000379844","Fagerhult, AB,FAG"));
        availableStocks.addElement(new BrokersStockEntry("SE0000224446","Fast Partner AB,FPAR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000431009","FB Industri Holding AB ser. B,FBI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000381840","Feelgood Svenska AB,FEEL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000104788","Fenix Outdoor AB ser. B,FIX B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000422107","Fingerprint Cards AB ser. B,FING B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000121816","Finnveden AB ser. B,FVED B"));
        availableStocks.addElement(new BrokersStockEntry("14555","Finnveden AB TR ser. B,FVED TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000395428","Firefly AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000522807","Focal Point AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000104846","Folkebolagen AB ser. B,FOLK B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000458390","Formo Medical AB,FORM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000141137","Forum SQL AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000495293","Framfab AB,FRAM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000545311","Frango AB,FRAN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000111171","Freetel AB ser B,FTEL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000111155","Freetel AB ser. A,FTEL A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000601544","Friluftsbolaget Ekelund &amp; Sagner AB,FRIL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000105116","Frontec AB ser. B,FTEC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000449639","Frontyard AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000242455","FöreningsSparbanken AB ser. A,FSPA A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000164477","Gambro AB ser. A,GAMB A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000164485","Gambro AB ser. B,GAMB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000202624","Getinge AB ser. B,GETI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000390270","GetUpdated Sweden AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000105264","Geveko, AB ser. B,GVKO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000835159","Glocalnet AB,GLOC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000428179","Glocalnet AB ser. B,GLOC B"));
        availableStocks.addElement(new BrokersStockEntry("13121","Glocalnet AB TR ser. B,GLOC TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000524530","Glycorex Transplantation AB ser. B,GTAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000388969","Gorthon Lines AB ser. B,GORT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000105371","Gotland, Rederiab. ser. A,GOTL A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000105397","Gotland, Rederiab. ser. B,GOTL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000610354","Graninge AB,GRAN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000195570","Gunnebo AB,GUNN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000350340","Gylling Optima Batteries AB ser. B,OPTB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000622656","Hagströmer &amp; Qviberg AB,HAGQ"));
        availableStocks.addElement(new BrokersStockEntry("SE0000105199","Haldex AB,HLDX"));
        availableStocks.addElement(new BrokersStockEntry("SE0000383259","Handelsbanken Hypotek AB pr,HBHY PREF"));
        availableStocks.addElement(new BrokersStockEntry("SE0000312043","Havsfrun, AB ser. B,HAV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000236515","Heba Fastighets AB ser. B,HEBA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000117582","Hebi Health Care AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000106270","Hennes &amp; Mauritz AB, H &amp; M ser. B,HM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000103699","Hexagon AB ser. B,HEXA B"));
        availableStocks.addElement(new BrokersStockEntry("18645","Hexagon AB TR ser. B,HEXA TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000461709","HiQ International AB,HIQ"));
        availableStocks.addElement(new BrokersStockEntry("SE0000214058","HL Display AB ser. B,HL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110322","HOIST INTERNATIONAL AB ser. B,HOST B"));
        availableStocks.addElement(new BrokersStockEntry("13829","HOIST International AB TRV ser. B,HOST TRVB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000171506","Holmen AB ser. A,HOLM A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000109290","Holmen AB ser. B,HOLM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000799827","HQ Fonder AB,HQFO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000170375","Hufvudstaden AB ser. A,HUFV A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000170383","Hufvudstaden AB ser. C,HUFV C"));
        availableStocks.addElement(new BrokersStockEntry("SE0000683757","Human Care H C AB,HUMA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000232175","Höganäs AB ser. B,HOGA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000678328","I.A.R Systems AB,IAR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000106759","IBS AB ser. B,IBS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000809501","ICM Logistik AB,ICM"));
        availableStocks.addElement(new BrokersStockEntry("18358","Icon Medialab Internatinal AB TR,ICON TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000476962","Icon Medialab International AB,ICON"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514747","IDL Biotech AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000680936","IDL Biotech AB TR ser. B,IDL TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000648107","Impact Europe Group AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000495962","INAC Instrumenteringar AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000396715","Independent Media Gr. Sweden AB ser. B,IMG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000189953","Industrial and Financial Syst. AB ser. A,IFS A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000189946","Industrial and Financial Syst. AB ser. B,IFS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000193187","Industrivärden, AB KVB ser. A,INDU KBA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000147696","Industrivärden, AB KVB ser. C,INDU KBC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000190126","Industrivärden, AB ser. A,INDU A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000107203","Industrivärden, AB ser. C,INDU C"));
        availableStocks.addElement(new BrokersStockEntry("SE0000396558","InfiniCom AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514481","InnovationsMSklarna AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000686768","Insite Interactive AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000135287","Intellecta AB ser. B,ICTA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000259418","Intelligent Micro Systems Data AB,IMS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000349243","Intentia International AB ser. B,INT B"));
        availableStocks.addElement(new BrokersStockEntry("12609","Intentia International AB TRB,INT TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000936478","Intrum Justitia AB,IJ"));
        availableStocks.addElement(new BrokersStockEntry("SE0000517591","inWarehouse AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000107401","Investor AB ser. A,INVE A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000107419","Investor AB ser. B,INVE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000164600","Invik &amp; Co AB ser. A,INVK A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000164626","Invik &amp; Co AB ser. B,INVK B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000275802","IRO AB,IRO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000119224","ITAB Industri AB ser. B,ITAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000107476","Jacobson &amp; Widmark, AB,JW"));
        availableStocks.addElement(new BrokersStockEntry("SE0000615858","JC AB,JC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000545626","Jeeves Information Systems AB,JEEV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000725624","JLT Mobile Computers AB,JLT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000109142","JM AB,JM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000806994","JM AB,JM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000695645","Jobline International AB,JOBL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000689986","Johnson Pump  AB,JP"));
        availableStocks.addElement(new BrokersStockEntry("11326","Johnson Pump AB ser. A,JP A"));
        availableStocks.addElement(new BrokersStockEntry("19765","Johnson Pump AB TRA,JP TRA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000393936","Johnson Pump Int. AB ser. B,JPI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000211682","JP Nordiska AB,JPNO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000107724","KABE Husvagnar AB ser. B,KABE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000102790","Kalmar Industries AB,KIND"));
        availableStocks.addElement(new BrokersStockEntry("SE0000347486","Karlshamns AB,KAB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000571416","Karo Bio AB,KARO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000242711","Karo Bio AB ser. B,KARO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000451346","Karolin Machine Tool AB,KMT"));
        availableStocks.addElement(new BrokersStockEntry("IS0000001469","Kaupþing banki hf.,KAUP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000418378","Kindwalls Bil AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120222","Kinnevik, Industriförvaltnings AB ser. A,KINV A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000104416","Kinnevik, Industriförvaltnings AB ser. B,KINV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000459067","Kipling Holding AB,KIPL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120727","Kjessler &amp; Mannerstråle AB,KM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000254567","KLIPPAN AB,KLIP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000957979","Klövern AB ser. A,KLOV A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000957987","Klövern AB ser. B,KLOV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000421273","Know IT AB,KNOW"));
        availableStocks.addElement(new BrokersStockEntry("14593","Know IT AB TR,KNOW TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000500779","Kopparbergs Bryggeri AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000856999","Kraftkommission i Sverige AB ser. B,KRK B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000549412","Kungsleden AB,KLED"));
        availableStocks.addElement(new BrokersStockEntry("SE0000426470","Labs2 Group AB,LABS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000808396","Lagercrantz Group AB ser B,LAGR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000106304","Latour, Investmentab. ser. A,LATO A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000106320","Latour, Investmentab. ser. B,LATO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000619371","LC-Tec Holding AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000251902","Ledstiernan AB ser. B,LEDS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000383499","LGP Telecom Holding AB,LGP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000469579","Lifco AB ser. B,LIF B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000819054","LifeAssays AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000476954","LightLab AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000349078","Limt AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108581","Lindab AB ser. B,LIND B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000267056","Lindex, AB,LDEX"));
        availableStocks.addElement(new BrokersStockEntry("SE0000311615","Linné Group AB,LINN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000191827","LjungbergGruppen AB ser. B,LJGR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000731770","Ludvika Mining AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108847","Lundbergföretagen AB, L E ser. B,LUND B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000100505","Lundin Oil AB ser. B,LOIL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000825820","Lundin Petroleum AB,LUPE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000861155","Lundin Petroleum AB BT,LUPE BT"));
        availableStocks.addElement(new BrokersStockEntry("15680","Lundin Petroleum AB TO,LUPE TO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000861148","Lundin Petroleum AB TR,LUPE TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000671745","Luvit AB,LUVA"));
        availableStocks.addElement(new BrokersStockEntry("19940","Luvit AB BT,LUVA BT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000767972","Luvit AB BTU,LUVA BTU"));
        availableStocks.addElement(new BrokersStockEntry("SE0000767964","Luvit AB TRU,LUVA TRU"));
        availableStocks.addElement(new BrokersStockEntry("SE0000168304","Luxonen S.A. SDB,LUXO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000442931","M2S Sverige AB ser. B,M2S B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000767873","Magic House AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000507659","Malmbergs Elektriska AB ser. B,MEAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000456386","Mandamus Fastigheter AB,MFAS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000232282","Matteus AB,MATT"));
        availableStocks.addElement(new BrokersStockEntry("US57772M1071","Maxim Pharmaceuticals, Inc.,MAXM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000221723","Meda AB ser. A,MEDA A"));
        availableStocks.addElement(new BrokersStockEntry("14765","Meda AB TR ser. A,MEDA TRA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000395170","MEDICOVER Holding S.A SDB,MCOV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000680969","MediRox AB ser. A,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000273294","Medivir AB ser. B,MVIR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000426454","Megacon AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000670580","Mekonomen AB,MEKO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000696841","Metro International S.A SDB ser. A,MTRO A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000696858","Metro International S.A SDB ser. B,MTRO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000526626","Micro Systemation AB ser. B,MSAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000375115","Micronic Laser Systems AB,MICR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000122657","Midway Holding AB ser. A,MIDW A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000122673","Midway Holding AB ser. B,MIDW B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000673998","Mind AB,MIND"));
        availableStocks.addElement(new BrokersStockEntry("SE0000294613","MiniDoc AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000587339","Miss Mary of Sweden Holding AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000886897","MNW Records Group AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000412363","Modern Times Group MTG AB ser. A,MTG A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000412371","Modern Times Group MTG AB ser. B,MTG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000345902","Modul 1 Data AB,MOD1"));
        availableStocks.addElement(new BrokersStockEntry("SE0000671810","Mogul AB,MOGL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000235574","Monark Stiga AB,MOST"));
        availableStocks.addElement(new BrokersStockEntry("SE0000672115","Morphic Technologies AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000395105","MSC Konsult AB ser. B,MSC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000374993","MTV Produktion AB ser. B,MTVP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000353898","MultiQ International AB,MULQ"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514507","Multisimplex AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000220824","Munksjö AB,MUNK"));
        availableStocks.addElement(new BrokersStockEntry("SE0000416604","Munters AB,MTRS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000672024","Music Bay AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000538845","Naturkompaniet AB,NATK"));
        availableStocks.addElement(new BrokersStockEntry("SE0000118952","NCC AB ser. A,NCC A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000117970","NCC AB ser. B,NCC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000162786","Nefab AB ser. B,NEF B"));
        availableStocks.addElement(new BrokersStockEntry("11165","NeoNet AB,NEO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000594038","Net Capital AB ser. B,NCAP B"));
        availableStocks.addElement(new BrokersStockEntry("19034","Net Insight AB BT ser. B,NETI BTB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000366098","Net Insight AB ser. B,NETI B"));
        availableStocks.addElement(new BrokersStockEntry("19033","Net Insight AB TR ser. B,NETI TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000657140","Netonnet AB,NON"));
        availableStocks.addElement(new BrokersStockEntry("SE0000308298","Netrevelation Holding AB,NETR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000558173","Netwise AB ser. B,NETW B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000426546","New Wave Group AB ser. B,NEWA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000312068","NFO Drives AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000402448","NGS Next Generation System Sweden AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000390296","NIBE Industrier AB ser. B,NIBE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000418402","Nilörngruppen AB ser. B,NILG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000226367","Nobel Biocare AB,NOBE"));
        availableStocks.addElement(new BrokersStockEntry("CH0014030040","Nobel Biocare Holding AG,NOBE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000949331","Nobia AB,NOBI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000373128","NOCOM AB ser. B,NOCM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000539942","Nokia Abp, SDB,NOKI"));
        availableStocks.addElement(new BrokersStockEntry("SE0000109811","Nolato AB ser. B,NOLA B"));
        availableStocks.addElement(new BrokersStockEntry("18359","Nolato AB ser. B TRB,NOLA TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000427361","Nordea AB,NDA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000588147","Nordea AB EUR,NDA E"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514572","Nordic Growth Market NGM Holding AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000396822","Nordic Shoes &amp; Accessories AB ser. B,NSA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000239733","Nordifagruppen AB ser. A,NOFA A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000239741","Nordifagruppen AB ser. B,NOFA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000371338","NordiTube Technologies AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000371296","Nordnet AB ser. B,NN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000350696","Norrporten, Fastighetsab,NORP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000147530","Norsk Hydro ASA SDB,HYDR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000383531","North Atlantic Natural Resources AB,NAN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000362675","NovaCast AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000507774","Novada AB,NOVA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514689","Novestra, AB,NOVE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000567752","NOVOTEK AB ser. B,NTEK B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000469132","NovyRost Investment Ltd,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000189128","Närkes Elektriska AB ser. B,NEA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514705","Obducat AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000291486","Observer AB,OBS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000381782","Observer AB ser. A,OBS A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000381790","Observer AB ser. B,OBS B"));
        availableStocks.addElement(new BrokersStockEntry("18112","Observer AB TR,OBS TR"));
        availableStocks.addElement(new BrokersStockEntry("CH0011449078","Obtech Medical AG,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000751968","Oden Control AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110116","OEM International AB ser. B,OEM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110165","OM AB,OM"));
        availableStocks.addElement(new BrokersStockEntry("SE0000426652","Opcon AB,OPCO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000304750","Optimail AB ser. A,OPTI A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000481079","Optimum Optik AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000486607","Optovent AB ser. B,OPVE B"));
        availableStocks.addElement(new BrokersStockEntry("11160","Orc Software AB,ORC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000188930","Ortivus AB ser. A,ORTI A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000123085","Ortivus AB ser. B,ORTI B"));
        availableStocks.addElement(new BrokersStockEntry("US6918281071","Oxigene, Inc.,OXGN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000265217","PA Resources AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000394181","Pandox  AB,PAND"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514655","Parisab AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000394165","PartnerTech AB,PART"));
        availableStocks.addElement(new BrokersStockEntry("SE0000106205","Peab AB ser. B,PEAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000590416","Perbio Science AB,PBIO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000809881","Pergo AB,PERG"));
        availableStocks.addElement(new BrokersStockEntry("17316","Pergo AB TR,PERG TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000544678","Persea AB ser. B,PSEA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110710","Perstorp AB ser. A,PERS A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110736","Perstorp AB ser. B,PERS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000289928","Pharmacia &amp; Upjohn, Inc. SDB,PHU"));
        availableStocks.addElement(new BrokersStockEntry("SE0000634040","Pharmacia Corporation SDB,PHA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000204828","Piren AB,PIRE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000110959","Platzer Fastigheter AB ser. B,PLAT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000567539","Poolia AB ser. B,POOL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000685828","Powerit PS AB,POWI"));
        availableStocks.addElement(new BrokersStockEntry("20108","Precise Biometrics AB BT ser. A,PREC BTA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000520769","Precise Biometrics AB ser. A,PREC A"));
        availableStocks.addElement(new BrokersStockEntry("20106","Precise Biometrics AB TR ser. A,PREC TRA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000356008","Prevas AB ser. B,PREV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000233934","Pricer AB ser. B,PRIC B"));
        availableStocks.addElement(new BrokersStockEntry("17804","Pricer TR ser. B,PRIC TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000648669","Printcom AB,TIME"));
        availableStocks.addElement(new BrokersStockEntry("SE0000412991","ProAct IT Group AB,PACT"));
        availableStocks.addElement(new BrokersStockEntry("13222","ProAct IT Group AB TR,PACT TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000459299","Probi AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000470700","Proffice AB ser. B,PROE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000393860","ProfilGruppen AB ser. B,PROF B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000374704","Pronyx AB,PRYX"));
        availableStocks.addElement(new BrokersStockEntry("18075","Pronyx AB TRV,PRYX TRV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000969289","Prosolutions AB BT,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000387607","Protect Data AB,PROT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000240772","Provobis Hotel &amp; Restauranger AB ser. B,PHOT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000430894","Pure Water Technology AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000796088","Push Development AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000454753","PyroSequencing AB ser. A,PYRO A"));
        availableStocks.addElement(new BrokersStockEntry("FI0009006696","Pöyry Group Oyj, Jaakko,JAP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000426462","Q-Med AB,QMED"));
        availableStocks.addElement(new BrokersStockEntry("SE0000191090","Ratos AB ser. A,RATO A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000111940","Ratos AB ser. B,RATO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000479107","ReadSoft AB ser. B,RSOF B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000950578","Realia AB,COLU"));
        availableStocks.addElement(new BrokersStockEntry("SE0000191298","Realia AB ser. A,REAL A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000193286","Realia AB ser. B,REAL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000628984","Reguard AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000795411","Rene Wable Energy in Sweden AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000262446","Resco AB ser. B,RESC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000373473","Riddarhyttan Resources AB,RHYT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000383473","Riddarhyttan Resources AB,RHYT"));
        availableStocks.addElement(new BrokersStockEntry("14655","Riddarhyttan Resources AB TR,RHYT TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000581290","Rindi Energi AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000484305","RKS AB ser. B,RKS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000401622","rnb Retail and Brands AB,RNBS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000683732","Robux IT Holding AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000112252","Rottneros AB,RROS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000387318","Rörvik Timber AB ser. B,RTIM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000112385","SAAB AB ser. B,SAAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000147555","Saint-Gobain, Compagnie de SDB,SAGO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000314502","SalusAnsvar AB ser. B,SALA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000667891","Sandvik AB,SAND"));
        availableStocks.addElement(new BrokersStockEntry("SE0000266991","Sapa AB,SAPA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000112682","Sardus, AB,SARD"));
        availableStocks.addElement(new BrokersStockEntry("SE0000805574","SAS AB,SAS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000329146","SAS Sverige AB,USAS"));
        availableStocks.addElement(new BrokersStockEntry("SE0000518425","Satsafe MLS AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514424","SBT i Landskrona AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120859","Scandiaconsult AB,SCC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000351157","Scandic Hotels AB,SHOT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000673907","Scandinavia Online AB,SCOL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000308272","SCANIA AB ser. A,SCV A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000308280","SCANIA AB ser. B,SCV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000352809","ScanMining  AB,SCMI"));
        availableStocks.addElement(new BrokersStockEntry("15282","ScanMining AB TR,SCMI TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000188500","Scribona AB ser. A,SCRI A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000188518","Scribona AB ser. B,SCRI B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000590630","Sea Power International AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000118838","Seco Tools AB ser. B,SECO B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000408189","SECTRA AB ser B,SECT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000163594","Securitas AB ser. B,SECU B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000264574","Segerström &amp; Svensson, AB ser. B,SEGE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000379497","Semcon AB,SEMC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000242133","Senea AB,SENE"));
        availableStocks.addElement(new BrokersStockEntry("14872","Senea AB BT,SENE BT"));
        availableStocks.addElement(new BrokersStockEntry("14871","Senea AB TR,SENE TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000567729","Sensys Traffic AB,SENS"));
        availableStocks.addElement(new BrokersStockEntry("17272","Sensys Traffic AB UR,SENS UR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000835217","Sigma AB ser. B,SIGM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000646606","Sign On i Stockholm AB,SION"));
        availableStocks.addElement(new BrokersStockEntry("18608","Sign On i Stockholm AB TR,SION TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000950982","SinterCast AB,SINT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000166506","SinterCast AB ser. A,SINT A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000166514","SinterCast AB ser. B,SINT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000113094","Skandia Försäkringsab,SDIA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000148884","Skandinaviska Enskilda Banken ser. A,SEB A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120784","Skandinaviska Enskilda Banken ser. C,SEB C"));
        availableStocks.addElement(new BrokersStockEntry("SE0000535593","Skanditek Industriförvaltning AB.,STEK"));
        availableStocks.addElement(new BrokersStockEntry("SE0000113250","Skanska AB ser. B,SKA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108201","SKF, AB ser. A,SKF A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108227","SKF, AB ser. B,SKF B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000241614","SkiStar AB ser. B,SKIS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000542896","Skultuna Messingsbruk AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000630154","Sky Ventures AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000476228","Skåne-möllan AB,SKMO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000480808","Smarteq AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000745143","Snapcat AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000749988","Snapcat AB Bet. Teckn. aktier,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000478059","Société Euro. de Communication, SDB A,SEC A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000478067","Société Euro. de Communication, SDB B,SEC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000454886","Sodra Petroleum AB,SODR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000323305","Softronic AB ser. B,SOF B"));
        availableStocks.addElement(new BrokersStockEntry("14525","Softronic AB TR ser.B,SOF TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000434102","Song Networks Holding AB,SONW"));
        availableStocks.addElement(new BrokersStockEntry("NO0003057200","SPCS-Gruppen ASA,SPCS ASA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000113516","Spendrups Bryggeriab. ser. B,SPEN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000384372","SRAB Holding AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000588063","SRAB Holding AV KVB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000171100","SSAB Svenskt Stål AB ser. A,SSAB A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120669","SSAB Svenskt Stål AB ser. B,SSAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000667875","Starbreeze AB,STAR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000116949","Stena Line AB ser. B,SLAB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000998650","Stille AB,null"));
        availableStocks.addElement(new BrokersStockEntry("FI0009007603","Stora Enso Oyj ser. A,STE A"));
        availableStocks.addElement(new BrokersStockEntry("FI0009005953","Stora Enso Oyj ser. AE,STE AE"));
        availableStocks.addElement(new BrokersStockEntry("FI0009007611","Stora Enso Oyj ser. R,STE R"));
        availableStocks.addElement(new BrokersStockEntry("FI0009005961","Stora Enso Oyj ser. RE,STE RE"));
        availableStocks.addElement(new BrokersStockEntry("SE0001045451","Strand Interconnect AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000113797","Strålfors AB ser. B,STRA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000653230","Studsvik AB,SVIK"));
        availableStocks.addElement(new BrokersStockEntry("SE0000489080","SWECO AB ser. A,SWEC A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000489098","SWECO AB ser. B,SWEC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108169","Svedala Industri AB,SVDA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000407991","Svedbergs i Dalstorp AB ser. B,SVED B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000310336","Swedish Match AB,SWMA"));
        availableStocks.addElement(new BrokersStockEntry("SE0000543878","Svensk Vodka i Motala AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000171886","Svenska Cellulosa AB SCA ser. A,SCA A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000112724","Svenska Cellulosa AB SCA ser. B,SCA B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000193120","Svenska Handelsbanken ser. A,SHB A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000152084","Svenska Handelsbanken ser. B,SHB B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000841447","Svenska Kaolin AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000416125","Svenska Orient Linien AB ser. B,SOL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000469959","SwitchCore AB,SCOR"));
        availableStocks.addElement(new BrokersStockEntry("13231","SwitchCore AB TR,SCOR TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000205932","Svolder AB ser. A,SVOL A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000205940","Svolder AB ser. B,SVOL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000114431","Sydkraft AB ser. A,SYD A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000114456","Sydkraft AB ser. C,SYD C"));
        availableStocks.addElement(new BrokersStockEntry("11238","Syngenta AG,SYN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000909947","Syrico AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000379075","SäkI AB,SAEK"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514408","TagMaster AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000135485","Taurus Petroleum AB ser. B,TAUR B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000433914","Technology Nexus AB,NEXU"));
        availableStocks.addElement(new BrokersStockEntry("12746","teckningsrStter ser. B i Getinge Industrier AB,GIND TRB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000314304","Tele2 AB ser. A,TEL2 A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000314312","Tele2 AB ser. B,TEL2 B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000366254","Teleca AB ser. B,TELC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000468571","Telelogic AB,TLOG"));
        availableStocks.addElement(new BrokersStockEntry("14251","Telelogic AB BT,TLOG BT"));
        availableStocks.addElement(new BrokersStockEntry("14249","Telelogic AB TR,TLOG TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000667925","TeliaSonera AB,TLSN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000434342","Teligent AB,TGNT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000333333","Testbolag_5 AB,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000483943","Thalamus Networks AB ser. B,THAL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000378127","Ticket Travel Group AB,TICK"));
        availableStocks.addElement(new BrokersStockEntry("FI0009000277","TietoEnator Abp,TIEN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000114662","Tivox AB ser. B,TIVO B"));
        availableStocks.addElement(new BrokersStockEntry("14935","TMT One AB SR ser. A,TMT1 SR1"));
        availableStocks.addElement(new BrokersStockEntry("SE0000311417","Tornet, Fastighets AB,TORN"));
        availableStocks.addElement(new BrokersStockEntry("SE0000564155","TPC Security AB,TPC"));
        availableStocks.addElement(new BrokersStockEntry("SE0000674475","TPC Security AB BT,TPC BT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000674467","TPC Security AB TR,TPC TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000391716","Traction AB ser. B,TRAC B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000818023","Transcom WorldWide S.A SDB ser. A,TWW A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000818031","Transcom WorldWide S.A SDB ser. B,TWW B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514549","TransLink Holding AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000114837","Trelleborg AB ser. B,TREL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000192403","Tricorona Mineral AB ser. B,TRIM B"));
        availableStocks.addElement(new BrokersStockEntry("14532","Tricorona Mineral AB SR2 ser.B,TRIM SR2"));
        availableStocks.addElement(new BrokersStockEntry("SE0000282071","Trio AB,TRIO"));
        availableStocks.addElement(new BrokersStockEntry("SE0000614695","Tripep AB,TPEP"));
        availableStocks.addElement(new BrokersStockEntry("SE0000166555","Trustor AB ser. B,TRUS B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000684664","Turkronan AB:s akt. ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000108300","TurnIT AB ser. B,TURN B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000233082","TV4 AB ser. A,TV4 A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000540551","Utfors AB,UTFO"));
        availableStocks.addElement(new BrokersStockEntry("15995","Utfors AB TR,UTFO TR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115008","Wallenstam Byggnads AB., Lennart ser. B,WALL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115107","VBG AB ser. B,VBG B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000120776","Westergyllen, AB ser. B,WEST B"));
        availableStocks.addElement(new BrokersStockEntry("11222","Wihlborg Fastigheter AB IA ser. B,WIHL IAB"));
        availableStocks.addElement(new BrokersStockEntry("SE0000950636","Wihlborgs Fastigheter AB,WIHL"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115354","Wihlborgs Fastigheter AB ser. B,WIHL B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000582603","Viking Telecom AB,VIKT"));
        availableStocks.addElement(new BrokersStockEntry("SE0000565210","Wilh. Sonesson AB ser. A,WSON A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000565228","Wilh. Sonesson AB ser. B,WSON B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000502312","Virtual Genetics Laboratory AB,VIGE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000640369","Vision Park Entertainment AB,VPE"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514630","Vitec i Umes AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000816043","Vitrolife AB,VITR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115222","VLT AB ser. B,VLT B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115404","WM-data AB ser. B,WM B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115420","Volvo, AB ser. A,VOLV A"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115446","Volvo, AB ser. B,VOLV B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000901803","Vostok Energo Investment Ltd IR,ENRG IR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000901779","Vostok Energo Investment Ltd SDB,ENRG"));
        availableStocks.addElement(new BrokersStockEntry("17948","Vostok Energo Investment Ltd TO 1,ENRG TO1"));
        availableStocks.addElement(new BrokersStockEntry("SE0000367823","Vostok Nafta, Inv Ltd SDB,VOST"));
        availableStocks.addElement(new BrokersStockEntry("SE0000739294","Vostok Oil Ltd IR,VOIL IR"));
        availableStocks.addElement(new BrokersStockEntry("SE0000739286","Vostok Oil Ltd SDB,VOIL"));
        availableStocks.addElement(new BrokersStockEntry("18606","Vostok Oil Ltd TRV,VOIL TRV"));
        availableStocks.addElement(new BrokersStockEntry("SE0000224578","XponCard Group AB,XPON"));
        availableStocks.addElement(new BrokersStockEntry("SE0000514325","ZAPP AB ser. B,ZAPP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115503","ZETECO AB ser. B,ZETE B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000419152","Zip Structure AB ser. B,null"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115578","Ångpanneföreningen, AB ser. B,ANGP B"));
        availableStocks.addElement(new BrokersStockEntry("SE0000115610","Öresund, Investmentab,ORES"));
    };

    public void init(WebAppEnvironmentInterface environment) {
        this.environment = environment;
    }
    public String getStock(String fondPrefix) {
        try {
            //URL url =new URL("http://p233/StockServlet?do=login&name=erland&password=dnalre");
            //URL url = new URL("http://www.google.com/search?q=erland");
            //URL url =new URL("http://www.stockholmsborsen.se/stocklist.asp?lang=swe&list=SSE43&group=Kursnoteringar&listName=O-listan, samtliga");
            //URL url = new URL("http://www.stockholmsborsen.se/getHistory.asp?isin=SE0000105116");
            URL url = new URL("http://www.stockholmsborsen.se/Slutkurser/excel.asp?"+
                    "InstrumentID="+fondPrefix+
                    "&InstrumentType=1"+
                    "&From=1980-01-01"+
                    "&todate=2005-01-01");
            URLConnection conn = url.openConnection();
            conn.setDoInput(true);
            conn.setDoOutput(false);
            conn.setUseCaches(false);


            String s = System.getProperty("http.agent", "StockServlet/1.0");
            String s1 = System.getProperty("os.arch", "") + " [" + Locale.getDefault().getLanguage() + "] " + System.getProperty("os.name", "") + " " + System.getProperty("os.version", "") + "; Sun";
            s = s + " (" + s1 + ")";
            System.out.println(s);
            conn.setRequestProperty("User-Agent", s);
            conn.setRequestProperty("Content-Type","application/x-www-form-urlencoded");
            BufferedReader inSB = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            /*String line;
            while((line = inSB.readLine())!=null) {
                System.out.println(line);
            }*/
            String result = SBXMLEncoder.encodeStockData(inSB);
            //System.out.println(result);
            inSB.close();
            return result;
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public Iterator getAvailableStocks() {
        return availableStocks.iterator();
    }

    public String getName() {
        return environment.getResources().getParameter("brokers.sb.name");
    }
}
